from functools import partial
import sys
sys.path.append('_2025/backprop_3')
from geometric_dl_utils import *
from plane_folding_utils import *
from geometric_dl_utils_simplified import *
from polytope_intersection_utils import intersect_polytopes
from manimlib import *
import glob
import torch
CHILL_BROWN = '#948979'
YELLOW = '#ffd35a'
YELLOW_FADE = '#7f6a2d'
BLUE = '#65c8d0'
GREEN = '#6e9671'
CHILL_GREEN = '#6c946f'
CHILL_BLUE = '#3d5c6f'
FRESH_TAN = '#dfd0b9'
CYAN = '#00FFFF'
MAGENTA = '#FF00FF'
svg_path = '/Users/stephen/Stephencwelch Dropbox/welch_labs/backprop_3/graphics/to_manim'
graphics_dir = '/Users/stephen/Stephencwelch Dropbox/welch_labs/backprop_3/graphics/'
colors = [GREY, BLUE, GREEN, YELLOW, PURPLE, ORANGE, PINK, TEAL]

def surface_func_from_model_with_axes(u, v, model, layer_idx, neuron_idx, axes=None, viz_scale=0.5):
    input_tensor = torch.tensor([[u, v]], dtype=torch.float32)
    with torch.no_grad():
        x = input_tensor
        for i in range(layer_idx + 1):
            x = model.model[i](x)
        activation = x[0, neuron_idx].item()
        z = activation * viz_scale
        if axes is not None:
            return axes.c2p(u, v, z)
        else:
            return np.array([u, v, z])

class p23b(InteractiveScene):

    def construct(self):
        model_path = '_2025/backprop_3/models/2_1.pth'
        model = BaarleNet([2])
        model.load_state_dict(torch.load(model_path))
        w1 = model.model[0].weight.detach().numpy()
        b1 = model.model[0].bias.detach().numpy()
        w2 = model.model[2].weight.detach().numpy()
        b2 = model.model[2].bias.detach().numpy()
        viz_scales = [0.2, 0.2, 0.13]
        num_neurons = [2, 2, 2]
        surfaces = []
        surface_funcs = []
        for layer_idx in range(len(model.model)):
            s = Group()
            surface_funcs.append([])
            for neuron_idx in range(num_neurons[layer_idx]):
                surface_func = partial(surface_func_from_model, model=model, layer_idx=layer_idx, neuron_idx=neuron_idx, viz_scale=viz_scales[layer_idx])
                bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
                ts = TexturedSurface(bent_surface, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
                ts.set_shading(0, 0, 0).set_opacity(0.8)
                s.add(ts)
                surface_funcs[-1].append(surface_func)
            surfaces.append(s)
        polygons = {}
        polygons['-1.new_tiling'] = [np.array([[-1.0, -1, 0], [-1, 1, 0], [1, 1, 0], [1, -1, 0]])]
        for layer_id in range(len(model.model) // 2):
            polygons[str(layer_id) + '.linear_out'] = process_with_layers(model.model[:2 * layer_id + 1], polygons[str(layer_id - 1) + '.new_tiling'])
            polygons[str(layer_id) + '.split_polygons_nested'] = split_polygons_with_relu_simple(polygons[str(layer_id) + '.linear_out'])
            polygons[str(layer_id) + '.split_polygons_nested_clipped'] = clip_polygons(polygons[str(layer_id) + '.split_polygons_nested'])
            polygons[str(layer_id) + '.split_polygons_merged'] = merge_zero_regions(polygons[str(layer_id) + '.split_polygons_nested_clipped'])
            polygons[str(layer_id) + '.new_tiling'] = recompute_tiling_general(polygons[str(layer_id) + '.split_polygons_merged'])
            print('Retiled plane into ', str(len(polygons[str(layer_id) + '.new_tiling'])), ' polygons.')
        polygons[str(layer_id + 1) + '.linear_out'] = process_with_layers(model.model, polygons[str(layer_id) + '.new_tiling'])
        intersection_lines, new_2d_tiling, upper_polytope, indicator = intersect_polytopes(*polygons[str(layer_id + 1) + '.linear_out'])
        my_indicator, my_top_polygons = compute_top_polytope(model, new_2d_tiling)
        axes_1 = ThreeDAxes(x_range=[-1, 1, 1], y_range=[-1, 1, 1], z_range=[-1, 1, 1], width=2, height=2, depth=1.5, axis_config={'color': FRESH_TAN, 'include_ticks': False, 'include_numbers': False, 'include_tip': True, 'stroke_width': 4, 'tip_config': {'width': 0.08, 'length': 0.08}})
        axes_2 = ThreeDAxes(x_range=[-1, 1, 1], y_range=[-1, 1, 1], z_range=[-1, 1, 1], width=2, height=2, depth=1.5, axis_config={'color': FRESH_TAN, 'include_ticks': False, 'include_numbers': False, 'include_tip': True, 'stroke_width': 4, 'tip_config': {'width': 0.08, 'length': 0.08}})
        axes_1.move_to([0, 0, 1.7])
        axes_2.move_to([0, 0, -1.7])
        polygons_11_pts = []
        for p in polygons['0.linear_out'][0][0]:
            p[2] = p[2] * viz_scales[0]
            polygons_11_pts.append(axes_1.c2p(*p))
        polygons_11_pts = np.array(polygons_11_pts)
        polygons_11 = manim_polygons_from_np_list([polygons_11_pts], colors=[CYAN], viz_scale=1, opacity=0.3)
        polygons_12_pts = []
        for p in polygons['0.linear_out'][1][0]:
            p[2] = p[2] * viz_scales[0]
            polygons_12_pts.append(axes_2.c2p(*p))
        polygons_12_pts = np.array(polygons_12_pts)
        polygons_12 = manim_polygons_from_np_list([polygons_12_pts], colors=[YELLOW], viz_scale=1, opacity=0.3)
        surface_func_11 = partial(surface_func_from_model_with_axes, model=model, layer_idx=0, neuron_idx=0, axes=axes_1, viz_scale=viz_scales[0])
        bent_surface_11 = ParametricSurface(surface_func_11, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        surface_11 = TexturedSurface(bent_surface_11, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
        surface_11.set_shading(0, 0, 0).set_opacity(0.8)
        surface_func_12 = partial(surface_func_from_model_with_axes, model=model, layer_idx=0, neuron_idx=1, axes=axes_2, viz_scale=viz_scales[0])
        bent_surface_12 = ParametricSurface(surface_func_12, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        surface_12 = TexturedSurface(bent_surface_12, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
        surface_12.set_shading(0, 0, 0).set_opacity(0.8)
        joint_points_11 = get_relu_joint(w1[0, 0], w1[0, 1], b1[0], extent=1)
        joint_points_11a = axes_1.c2p(joint_points_11[0][0], joint_points_11[0][1], 0)
        joint_points_11b = axes_1.c2p(joint_points_11[1][0], joint_points_11[1][1], 0)
        joint_line_11 = DashedLine(start=joint_points_11a, end=joint_points_11b, color=WHITE, stroke_width=5, dash_length=0.08)
        joint_points_12 = get_relu_joint(w1[1, 0], w1[1, 1], b1[1], extent=1)
        joint_points_12a = axes_2.c2p(joint_points_12[0][0], joint_points_12[0][1], 0)
        joint_points_12b = axes_2.c2p(joint_points_12[1][0], joint_points_12[1][1], 0)
        joint_line_12 = DashedLine(start=joint_points_12a, end=joint_points_12b, color=WHITE, stroke_width=5, dash_length=0.08)
        polygons_21a = VGroup()
        for i in range(2):
            polygons_21_pts = []
            for p in polygons['0.split_polygons_nested'][0][0][i]:
                p[2] = p[2] * viz_scales[0]
                polygons_21_pts.append(axes_1.c2p(*p))
            polygons_21_pts = np.array(polygons_21_pts)
            polygons_21a.add(manim_polygons_from_np_list([polygons_21_pts], colors=[CYAN], viz_scale=1, opacity=0.3))
        polygons_22a = VGroup()
        for i in range(2):
            polygons_22_pts = []
            for p in polygons['0.split_polygons_nested'][1][0][i]:
                p[2] = p[2] * viz_scales[0]
                polygons_22_pts.append(axes_2.c2p(*p))
            polygons_22_pts = np.array(polygons_22_pts)
            polygons_22a.add(manim_polygons_from_np_list([polygons_22_pts], colors=[YELLOW], viz_scale=1, opacity=0.3))
        polygons_21b = VGroup()
        for i in range(2):
            polygons_21_pts = []
            for p in polygons['0.split_polygons_nested_clipped'][0][0][i]:
                p[2] = p[2] * viz_scales[0]
                polygons_21_pts.append(axes_1.c2p(*p))
            polygons_21_pts = np.array(polygons_21_pts)
            polygons_21b.add(manim_polygons_from_np_list([polygons_21_pts], colors=[CYAN], viz_scale=1, opacity=0.3))
        polygons_22b = VGroup()
        for i in range(2):
            polygons_22_pts = []
            for p in polygons['0.split_polygons_nested_clipped'][1][0][i]:
                p[2] = p[2] * viz_scales[0]
                polygons_22_pts.append(axes_2.c2p(*p))
            polygons_22_pts = np.array(polygons_22_pts)
            polygons_22b.add(manim_polygons_from_np_list([polygons_22_pts], colors=[YELLOW], viz_scale=1, opacity=0.3))
        surface_func_21 = partial(surface_func_from_model_with_axes, model=model, layer_idx=1, neuron_idx=0, axes=axes_1, viz_scale=viz_scales[0])
        bent_surface_21 = ParametricSurface(surface_func_21, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        surface_21 = TexturedSurface(bent_surface_21, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
        surface_21.set_shading(0, 0, 0).set_opacity(0.8)
        surface_func_22 = partial(surface_func_from_model_with_axes, model=model, layer_idx=1, neuron_idx=1, axes=axes_2, viz_scale=viz_scales[0])
        bent_surface_22 = ParametricSurface(surface_func_22, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        surface_22 = TexturedSurface(bent_surface_22, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
        surface_22.set_shading(0, 0, 0).set_opacity(0.8)
        surface_11_copy = surface_11.copy()
        polygons_21a_copy = polygons_21a.copy()
        polygons_11_copy = polygons_11.copy()
        surface_12_copy = surface_12.copy()
        polygons_22a_copy = polygons_22a.copy()
        polygons_12_copy = polygons_12.copy()
        surface_21_copy = surface_21.copy()
        surface_22_copy = surface_22.copy()
        self.frame.reorient(-53, 68, 0, (0.01, -0.1, 0.09), 5.58)
        self.add(surface_11, polygons_11, axes_1)
        self.add(surface_12, polygons_12, axes_2)
        self.wait()
        self.remove(polygons_11)
        self.add(polygons_21a)
        self.add(joint_line_11)
        self.play(ReplacementTransform(polygons_21a[1], polygons_21b[1]), ReplacementTransform(surface_11, surface_21), run_time=3.2)
        self.remove(polygons_21b)
        self.remove(polygons_21a)
        self.add(polygons_21b)
        self.remove(joint_line_11)
        self.add(joint_line_11)
        self.remove(axes_1)
        self.add(axes_1)
        self.wait()
        self.remove(polygons_12)
        self.add(polygons_22a)
        self.add(joint_line_12)
        self.play(ReplacementTransform(polygons_22a[1], polygons_22b[1]), ReplacementTransform(surface_12, surface_22), run_time=3.2)
        self.remove(polygons_22b)
        self.remove(polygons_22a)
        self.add(polygons_22b)
        self.remove(joint_line_12)
        self.add(joint_line_12)
        self.remove(axes_2)
        self.add(axes_2)
        self.wait()
        group_11 = Group(surface_21, polygons_21b, axes_1, joint_line_11)
        group_12 = Group(surface_22, polygons_22b, axes_2, joint_line_12)
        surface_11_copy.shift([0, 0, -0.9])
        polygons_21a_copy.shift([0, 0, -0.9])
        polygons_11_copy.shift([0, 0, -0.9])
        surface_12_copy.shift([0, 0, 0.9])
        polygons_22a_copy.shift([0, 0, 0.9])
        polygons_12_copy.shift([0, 0, 0.9])
        self.wait()
        self.play(self.frame.animate.reorient(0, 58, 0, (0.19, -0.12, -0.1), 3.82), axes_1.animate.shift([0, 0, -0.9]), joint_line_11.animate.shift([0, 0, -0.9]), ReplacementTransform(polygons_21b, polygons_21a_copy), ReplacementTransform(surface_21, surface_11_copy), axes_2.animate.shift([0, 0, 0.9]), joint_line_12.animate.shift([0, 0, 0.9]), ReplacementTransform(polygons_22b, polygons_22a_copy), ReplacementTransform(surface_22, surface_12_copy), run_time=4)
        self.remove(surface_11_copy)
        self.add(surface_11_copy)
        self.remove(polygons_21a_copy)
        self.add(polygons_11_copy)
        self.remove(axes_1)
        self.add(axes_1)
        self.remove(surface_12_copy)
        self.add(surface_12_copy)
        self.remove(polygons_22a_copy)
        self.add(polygons_12_copy)
        self.remove(axes_2)
        self.add(axes_2)
        self.remove(joint_line_11)
        self.add(joint_line_11)
        self.remove(joint_line_12)
        self.add(joint_line_12)
        self.wait()
        d1 = Dot(ORIGIN, radius=0.04, fill_color=MAGENTA)
        d1.move_to(axes_1.c2p(0.59, 0.4, -0.04))
        d1.rotate(-20 * DEGREES, [0, 1, 0])
        d2 = Dot(ORIGIN, radius=0.05, fill_color=MAGENTA)
        d2.move_to(axes_2.c2p(0.59, 0.4, -0.05))
        d2.rotate(20 * DEGREES, [1, 0, 0])
        self.wait()
        self.play(self.frame.animate.reorient(-37, 56, 0, (0.59, -0.49, -0.13), 3.75), FadeIn(d1), FadeIn(d2), run_time=4, rate_func=linear)
        self.wait()
        polygons_21a.shift([0, 0, -0.9])
        surface_21_copy.shift([0, 0, -0.9])
        polygons_22a.shift([0, 0, 0.9])
        surface_22_copy.shift([0, 0, 0.9])
        d1b = Dot(ORIGIN, radius=0.04, fill_color=MAGENTA)
        d1b.move_to(axes_1.c2p(0.59, 0.4, 0))
        d2b = Dot(ORIGIN, radius=0.05, fill_color=MAGENTA)
        d2b.move_to(axes_2.c2p(0.59, 0.4, 0))
        self.wait()
        self.remove(polygons_11_copy)
        self.add(polygons_21a_copy)
        self.play(ReplacementTransform(polygons_21a_copy, polygons_21a), ReplacementTransform(surface_11_copy, surface_21_copy), ReplacementTransform(d1, d1b), run_time=3.5)
        self.remove(polygons_21a)
        self.add(polygons_21a)
        self.remove(axes_1)
        self.add(axes_1)
        self.remove(joint_line_11)
        self.add(joint_line_11)
        self.remove(d1b)
        self.add(d1b)
        self.wait()
        self.remove(polygons_12_copy)
        self.add(polygons_22a_copy)
        self.play(ReplacementTransform(polygons_22a_copy, polygons_22a), ReplacementTransform(surface_12_copy, surface_22_copy), ReplacementTransform(d2, d2b), run_time=3.5)
        self.remove(polygons_22a)
        self.add(polygons_22a)
        self.remove(axes_2)
        self.add(axes_2)
        self.remove(joint_line_12)
        self.add(joint_line_12)
        self.remove(d2b)
        self.add(d2b)
        self.wait()
        joint_points_11 = get_relu_joint(w1[0, 0], w1[0, 1], b1[0], extent=1)
        group_11 = Group(surfaces[1][0])
        if len(joint_points_11) > 0:
            joint_line_11b = line_from_joint_points_1(joint_points_11).set_opacity(0.9)
            group_11.add(joint_line_11b)
        group_12 = Group(surfaces[1][1])
        joint_points_12 = get_relu_joint(w1[1, 0], w1[1, 1], b1[1], extent=1)
        if len(joint_points_12) > 0:
            joint_line_12b = line_from_joint_points_1(joint_points_12).set_opacity(0.9)
            group_12.add(joint_line_12b)
        group_11.shift([0, 0, 1.5])
        d1c = Dot([0.59, 0.4, 1.5], radius=0.04, fill_color=MAGENTA)
        d2c = Dot([0.59, 0.4, 0.0], radius=0.04, fill_color=MAGENTA)
        self.wait()
        self.remove(axes_1)
        self.remove(polygons_21a)
        self.remove(axes_2)
        self.remove(polygons_22a)
        self.play(ReplacementTransform(surface_21_copy, group_11[0]), ReplacementTransform(joint_line_11, group_11[1]), ReplacementTransform(d1b, d1c), ReplacementTransform(surface_22_copy, group_12[0]), ReplacementTransform(joint_line_12, group_12[1]), ReplacementTransform(d2b, d2c), self.frame.animate.reorient(-2, 46, 0, (3.11, 0.22, -0.73), 6.89), run_time=3, rate_func=linear)
        self.wait()
        self.wait(20)
        self.embed()

class p25(InteractiveScene):

    def construct(self):
        model_path = '_2025/backprop_3/models/2_1.pth'
        model = BaarleNet([2])
        model.load_state_dict(torch.load(model_path))
        w1 = model.model[0].weight.detach().numpy()
        b1 = model.model[0].bias.detach().numpy()
        w2 = model.model[2].weight.detach().numpy()
        b2 = model.model[2].bias.detach().numpy()
        viz_scales = [0.2, 0.2, 0.2]
        num_neurons = [2, 2, 2]
        surfaces = []
        surface_funcs = []
        for layer_idx in range(len(model.model)):
            s = Group()
            surface_funcs.append([])
            for neuron_idx in range(num_neurons[layer_idx]):
                surface_func = partial(surface_func_from_model, model=model, layer_idx=layer_idx, neuron_idx=neuron_idx, viz_scale=viz_scales[layer_idx])
                bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
                ts = TexturedSurface(bent_surface, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
                ts.set_shading(0, 0, 0).set_opacity(0.8)
                s.add(ts)
                surface_funcs[-1].append(surface_func)
            surfaces.append(s)
        polygons = {}
        polygons['-1.new_tiling'] = [np.array([[-1.0, -1, 0], [-1, 1, 0], [1, 1, 0], [1, -1, 0]])]
        for layer_id in range(len(model.model) // 2):
            polygons[str(layer_id) + '.linear_out'] = process_with_layers(model.model[:2 * layer_id + 1], polygons[str(layer_id - 1) + '.new_tiling'])
            polygons[str(layer_id) + '.split_polygons_nested'] = split_polygons_with_relu_simple(polygons[str(layer_id) + '.linear_out'])
            polygons[str(layer_id) + '.split_polygons_nested_clipped'] = clip_polygons(polygons[str(layer_id) + '.split_polygons_nested'])
            polygons[str(layer_id) + '.split_polygons_merged'] = merge_zero_regions(polygons[str(layer_id) + '.split_polygons_nested_clipped'])
            polygons[str(layer_id) + '.new_tiling'] = recompute_tiling_general(polygons[str(layer_id) + '.split_polygons_merged'])
            print('Retiled plane into ', str(len(polygons[str(layer_id) + '.new_tiling'])), ' polygons.')
        polygons[str(layer_id + 1) + '.linear_out'] = process_with_layers(model.model, polygons[str(layer_id) + '.new_tiling'])
        intersection_lines, new_2d_tiling, upper_polytope, indicator = intersect_polytopes(*polygons[str(layer_id + 1) + '.linear_out'])
        my_indicator, my_top_polygons = compute_top_polytope(model, new_2d_tiling)
        joint_points_11 = get_relu_joint(w1[0, 0], w1[0, 1], b1[0], extent=1)
        group_11 = Group(surfaces[1][0])
        if len(joint_points_11) > 0:
            joint_line_11 = line_from_joint_points_1(joint_points_11).set_opacity(0.9)
            group_11.add(joint_line_11)
        group_12 = Group(surfaces[1][1])
        joint_points_12 = get_relu_joint(w1[1, 0], w1[1, 1], b1[1], extent=1)
        if len(joint_points_12) > 0:
            joint_line_12 = line_from_joint_points_1(joint_points_12).set_opacity(0.9)
            group_12.add(joint_line_12)
        group_11.shift([0, 0, 1.5])
        polygons_21 = manim_polygons_from_np_list(polygons['1.linear_out'][0], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_21.shift([0, 0, 0.001])
        polygons_22 = manim_polygons_from_np_list(polygons['1.linear_out'][1], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_22.shift([0, 0, 0.001])
        group_21 = Group(surfaces[2][0], polygons_21)
        group_22 = Group(surfaces[2][1], polygons_22)
        group_21.shift([3.0, 0, 1.5])
        group_22.shift([3.0, 0, 0])
        group_21.set_opacity(0.5)
        group_22.set_opacity(0.5)
        group_31 = group_21.copy()
        group_31[1].set_color(BLUE)
        group_31.shift([3, 0, -0.75])
        group_32 = group_22.copy()
        group_32[1].set_color(YELLOW)
        group_32.shift([3, 0, 0.75])
        loops = order_closed_loops_with_closure(intersection_lines)
        lines = VGroup()
        for loop in loops:
            loop = loop * np.array([1, 1, viz_scales[2]])
            line = VMobject()
            line.set_points_as_corners(loop)
            line.set_stroke(color='#FF00FF', width=3)
            lines.add(line)
        lines.shift([6, 0, 0.75])
        group_31[0].set_opacity(0.9)
        group_32[0].set_opacity(0.9)
        group_31[1].set_opacity(0.4)
        group_32[1].set_opacity(0.4)
        bent_plane_joint_lines = VGroup()
        pre_move_lines = VGroup()
        line_start = polygons['1.linear_out'][0][1][1] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][1][2] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][1][1] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][1][2] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][0][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][0][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 0])
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][2][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][2][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines.add(joint_line)
        d1a = Dot([0.59, 0.4, 1.5], radius=0.05, fill_color=MAGENTA)
        d2a = Dot([0.59, 0.4, 0.0], radius=0.05, fill_color=MAGENTA)
        d1b = d1a.copy()
        d1b.shift([3, 0, 0 - 0.89 * viz_scales[1] + 0.06])
        d2b = d2a.copy()
        d2b.shift([3, 0, 0 + 0.03 * viz_scales[1]])
        d1c = d1b.copy()
        d1c.shift([3, 0, -0.75])
        d2c = d2b.copy()
        d2c.shift([3, 0, 0.75])
        self.frame.reorient(-2, 46, 0, (3.11, 0.22, -0.73), 6.89)
        self.wait()
        self.add(group_11[0], group_12[0], pre_move_lines, d1a, d2a)
        self.wait()
        self.wait()
        self.play(ReplacementTransform(surfaces[1][0].copy(), surfaces[2][0]), ReplacementTransform(surfaces[1][1].copy(), surfaces[2][0]), ReplacementTransform(pre_move_lines.copy(), bent_plane_joint_lines), ReplacementTransform(d1a.copy(), d1b), run_time=3)
        self.add(polygons_21)
        self.remove(bent_plane_joint_lines)
        self.add(bent_plane_joint_lines)
        self.wait()
        bent_plane_joint_lines_2 = VGroup()
        pre_move_lines_2 = VGroup()
        line_start = polygons['1.linear_out'][1][1][1] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][1][2] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0.0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][1][1] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][1][2] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][0][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0.0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][0][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 0])
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][2][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0.0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][2][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][2][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0.0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][2][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines_2.add(joint_line)
        self.wait()
        self.play(ReplacementTransform(surfaces[1][0].copy(), surfaces[2][1]), ReplacementTransform(surfaces[1][1].copy(), surfaces[2][1]), ReplacementTransform(pre_move_lines_2.copy(), bent_plane_joint_lines_2), ReplacementTransform(d2a.copy(), d2b), run_time=3)
        self.add(polygons_22)
        self.remove(bent_plane_joint_lines_2)
        self.add(bent_plane_joint_lines_2)
        self.wait()
        d1c.set_opacity(0.5)
        self.play(ReplacementTransform(group_21.copy(), group_31), ReplacementTransform(group_22.copy(), group_32), ReplacementTransform(d1b.copy(), d1c), ReplacementTransform(d2b.copy(), d2c), run_time=3.0)
        self.play(ShowCreation(lines))
        self.wait()
        self.play(self.frame.animate.reorient(-2, 36, 0, (6.96, 0.51, -0.16), 3.55), run_time=4)
        self.wait()
        self.play(self.frame.animate.reorient(-2, 46, 0, (3.16, 0.8, -0.13), 6.89), run_time=4)
        self.wait()
        self.wait()
        self.play(self.frame.animate.reorient(0, 0, 0, (0.13, -0.08, -0.18), 3.99), FadeOut(d2a), FadeOut(d2b), FadeOut(d2c), FadeOut(d1b), FadeOut(d1c), group_12.animate.set_opacity(0.0), pre_move_lines[1:3].animate.set_opacity(0.0), run_time=4)
        self.wait()
        self.play(FadeOut(d1a))
        d1a = Dot([0.3, 0.7, 1.5], radius=0.05, fill_color=MAGENTA)
        d2a = Dot([0.3, 0.7, 0.0 + viz_scales[1] * 0.82], radius=0.05, fill_color=MAGENTA)
        d2a.rotate(25 * DEGREES, [1, 0, 0])
        d1b = d1a.copy()
        d1b.shift([3, 0, 0 + 0.199 * viz_scales[1]])
        d1b.rotate(25 * DEGREES, [1, 0, 0])
        d2b = d2a.copy()
        d2b.shift([3, 0, 0 - 1.23 * viz_scales[1]])
        d2b.shift([0, 0, -0.15])
        d2b.rotate(-60 * DEGREES, [1, 0, 0])
        d1c = d1b.copy()
        d1c.shift([3, 0, -0.75])
        d2c = d2b.copy()
        d2c.shift([3, 0, 0.75])
        d2c.set_opacity(0.6)
        self.wait()
        self.play(FadeIn(d1a))
        self.wait()
        self.play(group_12.animate.set_opacity(0.8), pre_move_lines[1:3].animate.set_opacity(1.0), self.frame.animate.reorient(-1, 55, 0, (0.12, 0.12, 0.06), 3.05), FadeIn(d2a), run_time=4)
        self.wait()
        self.add(d1b, d2b, d1c, d2c)
        self.wait()
        self.play(self.frame.animate.reorient(0, 31, 0, (6.13, 0.13, 0.44), 3.52), run_time=4)
        self.wait()
        self.play(self.frame.animate.reorient(-1, 37, 0, (3.14, -0.4, -0.06), 6.37), run_time=4)
        self.wait()
        self.wait(20)
        self.embed()