from manimlib import *
from functools import partial
import sys
sys.path.append('_2025/backprop_3')
from geometric_dl_utils import *
from plane_folding_utils import *
from geometric_dl_utils_simplified import *
from polytope_intersection_utils import intersect_polytopes
WELCH_RED = '#EC2027'
graphics_dir = '/Users/stephen/Stephencwelch Dropbox/welch_labs/ai_book/4_deep_learning/graphics/baarle_hertog_maps/'
colors = [RED, BLUE, GREEN, YELLOW, PURPLE, ORANGE, PINK, TEAL]
map_filename = 'baarle_hertog_maps-13.png'

class p3_6_book_9(InteractiveScene):

    def construct(self):
        map_img = ImageMobject(graphics_dir + map_filename)
        map_img.set_height(2)
        map_img.set_width(2)
        map_img.move_to(ORIGIN)
        model = BaarleNet([3])
        w1 = np.array([[-2.00458, 2.24611], [-2.56046, -1.21349], [-1.94774, 0.716835]], dtype=np.float32)
        b1 = np.array([0.00728259, -1.38003, 1.77056], dtype=np.float32)
        w2 = np.array([[2.46867, 3.78735, -1.90977], [-2.55351, -2.95687, 1.74294]], dtype=np.float32)
        b2 = np.array([1.41342, -1.23457], dtype=np.float32)
        with torch.no_grad():
            model.model[0].weight.copy_(torch.from_numpy(w1))
            model.model[0].bias.copy_(torch.from_numpy(b1))
            model.model[2].weight.copy_(torch.from_numpy(w2))
            model.model[2].bias.copy_(torch.from_numpy(b2))
        viz_scales = [0.2, 0.2, 0.13]
        num_neurons = [3, 3, 2]
        surfaces = []
        surface_funcs = []
        for layer_idx in range(len(model.model)):
            s = Group()
            surface_funcs.append([])
            for neuron_idx in range(num_neurons[layer_idx]):
                surface_func = partial(surface_func_from_model, model=model, layer_idx=layer_idx, neuron_idx=neuron_idx, viz_scale=viz_scales[layer_idx])
                bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
                ts = TexturedSurface(bent_surface, graphics_dir + map_filename)
                ts.set_shading(0, 0, 0).set_opacity(0.8)
                s.add(ts)
                surface_funcs[-1].append(surface_func)
            surfaces.append(s)
        polygons = {}
        polygons['-1.new_tiling'] = [np.array([[-1.0, -1, 0], [-1, 1, 0], [1, 1, 0], [1, -1, 0]])]
        for layer_id in range(len(model.model) // 2):
            polygons[str(layer_id) + '.linear_out'] = process_with_layers(model.model[:2 * layer_id + 1], polygons[str(layer_id - 1) + '.new_tiling'])
            polygons[str(layer_id) + '.split_polygons_nested'] = split_polygons_with_relu_simple(polygons[str(layer_id) + '.linear_out'])
            polygons[str(layer_id) + '.split_polygons_nested_clipped'] = clip_polygons(polygons[str(layer_id) + '.split_polygons_nested'])
            polygons[str(layer_id) + '.split_polygons_merged'] = merge_zero_regions(polygons[str(layer_id) + '.split_polygons_nested_clipped'])
            polygons[str(layer_id) + '.new_tiling'] = recompute_tiling_general(polygons[str(layer_id) + '.split_polygons_merged'])
            print('Retiled plane into ', str(len(polygons[str(layer_id) + '.new_tiling'])), ' polygons.')
        polygons[str(layer_id + 1) + '.linear_out'] = process_with_layers(model.model, polygons[str(layer_id) + '.new_tiling'])
        intersection_lines, new_2d_tiling, upper_polytope, indicator = intersect_polytopes(*polygons[str(layer_id + 1) + '.linear_out'])
        my_indicator, my_top_polygons = compute_top_polytope(model, new_2d_tiling)
        joint_points_11 = get_relu_joint(w1[0, 0], w1[0, 1], b1[0], extent=1)
        joint_line_11 = line_from_joint_points_1(joint_points_11, stroke_width=8).set_opacity(0.9).set_color(WELCH_RED)
        group_11 = Group(surfaces[1][0], joint_line_11)
        joint_points_12 = get_relu_joint(w1[1, 0], w1[1, 1], b1[1], extent=1)
        joint_line_12 = line_from_joint_points_1(joint_points_12, stroke_width=8).set_opacity(0.9).set_color(WELCH_RED)
        group_12 = Group(surfaces[1][1], joint_line_12)
        joint_points_13 = get_relu_joint(w1[2, 0], w1[2, 1], b1[2], extent=1)
        joint_line_13 = line_from_joint_points_1(joint_points_13, stroke_width=8).set_opacity(0.9).set_color(WELCH_RED)
        group_13 = Group(surfaces[1][2], joint_line_13)
        surface_func = partial(surface_func_from_model, model=model, layer_idx=1, neuron_idx=0, viz_scale=w2[0, 0] * viz_scales[2])
        bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        scaled_surface_1 = TexturedSurface(bent_surface, graphics_dir + map_filename)
        scaled_surface_1.set_shading(0, 0, 0).set_opacity(0.9)
        scaled_surface_1.shift([3, 0, 1.5])
        surface_func = partial(surface_func_from_model, model=model, layer_idx=1, neuron_idx=1, viz_scale=w2[0, 1] * viz_scales[2])
        bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        scaled_surface_2 = TexturedSurface(bent_surface, graphics_dir + map_filename)
        scaled_surface_2.set_shading(0, 0, 0).set_opacity(0.9)
        scaled_surface_2.shift([3, 0, 0])
        surface_func = partial(surface_func_from_model, model=model, layer_idx=1, neuron_idx=2, viz_scale=w2[0, 2] * viz_scales[2])
        bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        scaled_surface_3 = TexturedSurface(bent_surface, graphics_dir + map_filename)
        scaled_surface_3.set_shading(0, 0, 0).set_opacity(0.9)
        scaled_surface_3.shift([3, 0, -1.5])
        group_11_scaled = Group(scaled_surface_1, joint_line_11.copy().shift([3, 0, 0]))
        group_12_scaled = Group(scaled_surface_2, joint_line_12.copy().shift([3, 0, 0]))
        group_13_scaled = Group(scaled_surface_3, joint_line_13.copy().shift([3, 0, 0]))
        bent_plane_joint_lines = VGroup()
        pre_move_lines = VGroup()
        line_start = polygons['1.linear_out'][0][0][2] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][0][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][2] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][0][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][1][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][1][4] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][1][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][1][4] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][2][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][2][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][4][2] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][4][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][4][2] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][4][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WELCH_RED, stroke_width=8, dash_length=0.05)
        pre_move_lines.add(joint_line)
        self.wait()
        self.wait()
        self.frame.reorient(0, 0, 0, (-0.0, 0.03, 0.0), 2.31)

        def flat_surf_func(u, v):
            return [u, v, 0]
        flat_map_surf = ParametricSurface(flat_surf_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        flat_map = TexturedSurface(flat_map_surf, graphics_dir + map_filename)
        flat_map.set_shading(0, 0, 0).set_opacity(0.8)
        self.add(flat_map)
        self.wait()
        self.remove(flat_map)
        self.frame.reorient(0, 54, 0, (0.0, 0.0, 0.0), 2.72)
        self.add(group_11[0])
        self.wait()
        self.remove(group_11[0])
        self.add(group_12[0])
        self.wait()
        self.remove(group_12[0])
        self.add(group_13[0])
        self.wait()
        self.remove(group_13[0])
        polygons_21 = manim_polygons_from_np_list(polygons['1.linear_out'][0], colors=colors, viz_scale=viz_scales[2])
        self.frame.reorient(0, 54, 0, (0.0, 0.0, 0.0), 2.72)
        self.add(surfaces[2][0])
        self.add(polygons_21)
        self.wait()
        self.remove(surfaces[2][0], bent_plane_joint_lines, polygons_21)
        self.frame.reorient(4, 41, 0, (-0.05, -0.18, -0.23), 2.72)
        polygons_22 = manim_polygons_from_np_list(polygons['1.linear_out'][1], colors=colors, viz_scale=viz_scales[2])
        self.add(surfaces[2][1])
        self.add(polygons_22)
        self.wait()
        axes_1 = ThreeDAxes(x_range=[-1.2, 1.2, 1], y_range=[-1.2, 1.2, 1], z_range=[-0.7, 0.7, 1], height=3.0, width=3.0, depth=1.8, axis_config={'include_ticks': False, 'color': CHILL_BROWN, 'stroke_width': 2, 'include_tip': True, 'tip_config': {'fill_opacity': 1, 'width': 0.1, 'length': 0.1}})
        intersection_points_raveled = np.array(intersection_lines).reshape(8, 3)
        intersection_points_raveled = intersection_points_raveled * np.array([1, 1, viz_scales[2]])
        intersection_points_raveled = intersection_points_raveled[(2, 6, 5, 1, 0), :]
        line = VMobject()
        line.set_points_as_corners(intersection_points_raveled)
        line.set_stroke(color='#FF00FF', width=5)
        surfaces[2][0].set_opacity(0.35)
        surfaces[2][1].set_opacity(0.5)
        polygons_21.set_color(BLUE)
        polygons_22.set_color(YELLOW)
        self.wait()
        self.add(surfaces[2][0])
        self.add(polygons_21)
        self.add(polygons_22)
        self.remove(line)
        self.remove(polygons_21, polygons_22)
        self.wait()
        self.frame.reorient(1, 41, 0, (-0.13, -0.06, -0.12), 2.69)
        self.wait()
        self.frame.reorient(2, 81, 0, (-0.08, -0.05, -0.07), 2.69)
        self.wait()

        def flat_surf_func(u, v):
            return [u, v, 0]
        flat_map_surf = ParametricSurface(flat_surf_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        flat_map = TexturedSurface(flat_map_surf, graphics_dir + map_filename)
        flat_map.set_shading(0, 0, 0).set_opacity(0.8)
        self.wait()
        self.remove(surfaces[2][0], surfaces[2][1], polygons_22, polygons_21)
        self.add(flat_map)
        self.add(line)
        self.frame.reorient(0, 0, 0, (-0.02, -0.03, 0.0), 2.22)
        self.wait()
        self.embed()