from functools import partial
import sys
sys.path.append('_2025/backprop_3')
from geometric_dl_utils import *
from plane_folding_utils import *
from geometric_dl_utils_simplified import *
from polytope_intersection_utils import intersect_polytopes
from manimlib import *
CHILL_BROWN = '#948979'
YELLOW = '#ffd35a'
YELLOW_FADE = '#7f6a2d'
BLUE = '#65c8d0'
GREEN = '#6e9671'
CHILL_GREEN = '#6c946f'
CHILL_BLUE = '#3d5c6f'
FRESH_TAN = '#dfd0b9'
CYAN = '#00FFFF'
graphics_dir = '/Users/stephen/Stephencwelch Dropbox/welch_labs/backprop_3/graphics/'
colors = [GREY, BLUE, GREEN, YELLOW, PURPLE, ORANGE, PINK, TEAL]

class p46(InteractiveScene):

    def construct(self):
        map_img = ImageMobject(graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
        map_img.set_height(2)
        map_img.set_width(2)
        map_img.move_to(ORIGIN)
        model = BaarleNet([2])
        w1 = np.array([[2.5135, -1.02481], [-1.4043, 2.41291]], dtype=np.float32)
        b1 = np.array([-1.23981, -0.450078], dtype=np.float32)
        w2 = np.array([[3.17024, 1.32567], [-3.40372, -1.53878]], dtype=np.float32)
        b2 = np.array([-0.884835, 0.0332228], dtype=np.float32)
        with torch.no_grad():
            model.model[0].weight.copy_(torch.from_numpy(w1))
            model.model[0].bias.copy_(torch.from_numpy(b1))
            model.model[2].weight.copy_(torch.from_numpy(w2))
            model.model[2].bias.copy_(torch.from_numpy(b2))
        viz_scales = [0.2, 0.2, 0.13]
        num_neurons = [2, 2, 2]
        surfaces = []
        surface_funcs = []
        for layer_idx in range(len(model.model)):
            s = Group()
            surface_funcs.append([])
            for neuron_idx in range(num_neurons[layer_idx]):
                surface_func = partial(surface_func_from_model, model=model, layer_idx=layer_idx, neuron_idx=neuron_idx, viz_scale=viz_scales[layer_idx])
                bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
                ts = TexturedSurface(bent_surface, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
                ts.set_shading(0, 0, 0).set_opacity(0.8)
                s.add(ts)
                surface_funcs[-1].append(surface_func)
            surfaces.append(s)
        polygons = {}
        polygons['-1.new_tiling'] = [np.array([[-1.0, -1, 0], [-1, 1, 0], [1, 1, 0], [1, -1, 0]])]
        for layer_id in range(len(model.model) // 2):
            polygons[str(layer_id) + '.linear_out'] = process_with_layers(model.model[:2 * layer_id + 1], polygons[str(layer_id - 1) + '.new_tiling'])
            polygons[str(layer_id) + '.split_polygons_nested'] = split_polygons_with_relu_simple(polygons[str(layer_id) + '.linear_out'])
            polygons[str(layer_id) + '.split_polygons_nested_clipped'] = clip_polygons(polygons[str(layer_id) + '.split_polygons_nested'])
            polygons[str(layer_id) + '.split_polygons_merged'] = merge_zero_regions(polygons[str(layer_id) + '.split_polygons_nested_clipped'])
            polygons[str(layer_id) + '.new_tiling'] = recompute_tiling_general(polygons[str(layer_id) + '.split_polygons_merged'])
            print('Retiled plane into ', str(len(polygons[str(layer_id) + '.new_tiling'])), ' polygons.')
        polygons[str(layer_id + 1) + '.linear_out'] = process_with_layers(model.model, polygons[str(layer_id) + '.new_tiling'])
        intersection_lines, new_2d_tiling, upper_polytope, indicator = intersect_polytopes(*polygons[str(layer_id + 1) + '.linear_out'])
        my_indicator, my_top_polygons = compute_top_polytope(model, new_2d_tiling)
        joint_points_11 = get_relu_joint(w1[0, 0], w1[0, 1], b1[0], extent=1)
        group_11 = Group(surfaces[1][0])
        if len(joint_points_11) > 0:
            joint_line_11 = line_from_joint_points_1(joint_points_11).set_opacity(0.9)
            group_11.add(joint_line_11)
        group_12 = Group(surfaces[1][1])
        joint_points_12 = get_relu_joint(w1[1, 0], w1[1, 1], b1[1], extent=1)
        if len(joint_points_12) > 0:
            joint_line_12 = line_from_joint_points_1(joint_points_12).set_opacity(0.9)
            group_12.add(joint_line_12)
        group_11.shift([0, 0, 1.5])
        polygons_21 = manim_polygons_from_np_list(polygons['1.linear_out'][0], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_21.shift([0, 0, 0.001])
        polygons_22 = manim_polygons_from_np_list(polygons['1.linear_out'][1], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_22.shift([0, 0, 0.001])
        group_21 = Group(surfaces[2][0], polygons_21)
        group_22 = Group(surfaces[2][1], polygons_22)
        group_21.shift([3.0, 0, 1.5])
        group_22.shift([3.0, 0, 0])
        group_21.set_opacity(0.5)
        group_22.set_opacity(0.5)
        group_31 = group_21.copy()
        group_31[1].set_color(BLUE)
        group_31.shift([3, 0, -0.75])
        group_32 = group_22.copy()
        group_32[1].set_color(YELLOW)
        group_32.shift([3, 0, 0.75])
        loops = order_closed_loops_with_closure(intersection_lines)
        lines = VGroup()
        for loop in loops:
            loop = loop * np.array([1, 1, viz_scales[2]])
            line = VMobject()
            line.set_points_as_corners(loop)
            line.set_stroke(color='#FF00FF', width=5)
            lines.add(line)
        lines.shift([6, 0, 0.75])
        group_31[0].set_opacity(0.9)
        group_32[0].set_opacity(0.9)
        group_31[1].set_opacity(0.4)
        group_32[1].set_opacity(0.4)
        bent_plane_joint_lines = VGroup()
        pre_move_lines = VGroup()
        line_start = polygons['1.linear_out'][0][1][1] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][1][2] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][1][1] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][1][2] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][0][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][0][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 0])
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][2][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][2][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines.add(joint_line)
        self.frame.reorient(-2, 46, 0, (3.11, 0.22, -0.73), 6.89)
        self.wait()
        self.play(FadeIn(group_11[0]), FadeIn(group_12[0]), FadeIn(pre_move_lines))
        self.wait()
        self.wait()
        self.play(ReplacementTransform(surfaces[1][0].copy(), surfaces[2][0]), ReplacementTransform(surfaces[1][1].copy(), surfaces[2][0]), ReplacementTransform(pre_move_lines.copy(), bent_plane_joint_lines), run_time=3)
        self.add(polygons_21)
        self.remove(bent_plane_joint_lines)
        self.add(bent_plane_joint_lines)
        self.wait()
        bent_plane_joint_lines_2 = VGroup()
        pre_move_lines_2 = VGroup()
        line_start = polygons['1.linear_out'][1][1][1] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][1][2] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0.0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][1][1] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][1][2] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][0][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0.0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][0][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 0])
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][2][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0.0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][2][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][2][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0.0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][2][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines_2.add(joint_line)
        self.wait()
        self.play(ReplacementTransform(surfaces[1][0].copy(), surfaces[2][1]), ReplacementTransform(surfaces[1][1].copy(), surfaces[2][1]), ReplacementTransform(pre_move_lines_2.copy(), bent_plane_joint_lines_2), run_time=3)
        self.add(polygons_22)
        self.remove(bent_plane_joint_lines_2)
        self.add(bent_plane_joint_lines_2)
        self.wait()
        self.play(ReplacementTransform(group_21.copy(), group_31), ReplacementTransform(group_22.copy(), group_32), run_time=3.0)
        self.play(ShowCreation(lines))
        self.wait()
        self.wait(20)
        self.embed()

class p47b(InteractiveScene):

    def construct(self):
        map_img = ImageMobject(graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
        map_img.set_height(2)
        map_img.set_width(2)
        map_img.move_to(ORIGIN)
        model_path = '_2025/backprop_3/models/2_2_1.pth'
        model = BaarleNet([2, 2])
        model.load_state_dict(torch.load(model_path))
        viz_scales = [0.25, 0.25, 0.3, 0.3, 0.15]
        num_neurons = [2, 2, 2, 2, 2]
        w1 = model.model[0].weight.detach().numpy()
        b1 = model.model[0].bias.detach().numpy()
        w2 = model.model[2].weight.detach().numpy()
        b2 = model.model[2].bias.detach().numpy()
        surfaces = []
        surface_funcs = []
        for layer_idx in range(len(model.model)):
            s = Group()
            surface_funcs.append([])
            for neuron_idx in range(num_neurons[layer_idx]):
                surface_func = partial(surface_func_from_model, model=model, layer_idx=layer_idx, neuron_idx=neuron_idx, viz_scale=viz_scales[layer_idx])
                bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
                ts = TexturedSurface(bent_surface, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
                ts.set_shading(0, 0, 0).set_opacity(0.8)
                s.add(ts)
                surface_funcs[-1].append(surface_func)
            surfaces.append(s)
        polygons = {}
        polygons['-1.new_tiling'] = [np.array([[-1.0, -1, 0], [-1, 1, 0], [1, 1, 0], [1, -1, 0]])]
        for layer_id in range(len(model.model) // 2):
            polygons[str(layer_id) + '.linear_out'] = process_with_layers(model.model[:2 * layer_id + 1], polygons[str(layer_id - 1) + '.new_tiling'])
            polygons[str(layer_id) + '.split_polygons_nested'] = split_polygons_with_relu_simple(polygons[str(layer_id) + '.linear_out'])
            polygons[str(layer_id) + '.split_polygons_nested_clipped'] = clip_polygons(polygons[str(layer_id) + '.split_polygons_nested'])
            polygons[str(layer_id) + '.split_polygons_merged'] = merge_zero_regions(polygons[str(layer_id) + '.split_polygons_nested_clipped'])
            polygons[str(layer_id) + '.new_tiling'] = recompute_tiling_general(polygons[str(layer_id) + '.split_polygons_merged'])
            print('Retiled plane into ', str(len(polygons[str(layer_id) + '.new_tiling'])), ' polygons.')
        polygons[str(layer_id + 1) + '.linear_out'] = process_with_layers(model.model, polygons[str(layer_id) + '.new_tiling'])
        intersection_lines, new_2d_tiling, upper_polytope, indicator = intersect_polytopes(*polygons[str(layer_id + 1) + '.linear_out'])
        my_indicator, my_top_polygons = compute_top_polytope(model, new_2d_tiling)
        joint_points_11 = get_relu_joint(w1[0, 0], w1[0, 1], b1[0], extent=1)
        group_11 = Group(surfaces[1][0])
        if len(joint_points_11) > 0:
            joint_line_11 = line_from_joint_points_1(joint_points_11).set_opacity(0.9)
            group_11.add(joint_line_11)
        group_12 = Group(surfaces[1][1])
        joint_points_12 = get_relu_joint(w1[1, 0], w1[1, 1], b1[1], extent=1)
        if len(joint_points_12) > 0:
            joint_line_12 = line_from_joint_points_1(joint_points_12).set_opacity(0.9)
            group_12.add(joint_line_12)
        group_11.shift([0, 0, 1.5])
        polygons_21 = manim_polygons_from_np_list(polygons['1.linear_out'][0], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_21.shift([0, 0, 0.001])
        polygons_22 = manim_polygons_from_np_list(polygons['1.linear_out'][1], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_22.shift([0, 0, 0.001])
        group_21 = Group(surfaces[2][0], polygons_21)
        group_22 = Group(surfaces[2][1], polygons_22)
        group_21.shift([3.0, 0, 1.5])
        group_22.shift([3.0, 0, 0])
        group_21.set_opacity(0.5)
        group_22.set_opacity(0.5)
        group_31_fakeout = group_21.copy()
        group_31_fakeout[1].set_color(BLUE)
        group_31_fakeout.shift([3, 0, -0.75])
        group_32_fakeout = group_22.copy()
        group_32_fakeout[1].set_color(YELLOW)
        group_32_fakeout.shift([3, 0, 0.75])
        group_31_fakeout[0].set_opacity(0.9)
        group_32_fakeout[0].set_opacity(0.9)
        group_31_fakeout[1].set_opacity(0.4)
        group_32_fakeout[1].set_opacity(0.4)
        bent_plane_joint_lines = VGroup()
        pre_move_lines = VGroup()
        line_start = polygons['1.linear_out'][0][1][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][1][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][1][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][1][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][0][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][0][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][2] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][0][3] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][2] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][0][3] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines.add(joint_line)
        self.frame.reorient(-2, 46, 0, (3.11, 0.22, -0.73), 6.89)
        self.wait()
        self.play(FadeIn(group_11[0]), FadeIn(group_12[0]), FadeIn(pre_move_lines))
        self.wait()
        self.wait()
        self.play(ReplacementTransform(surfaces[1][0].copy(), surfaces[2][0]), ReplacementTransform(surfaces[1][1].copy(), surfaces[2][0]), ReplacementTransform(pre_move_lines.copy(), bent_plane_joint_lines), run_time=3)
        self.add(polygons_21)
        self.remove(bent_plane_joint_lines)
        self.add(bent_plane_joint_lines)
        self.wait()
        bent_plane_joint_lines_2 = VGroup()
        pre_move_lines_2 = VGroup()
        line_start = polygons['1.linear_out'][1][1][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][1][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][1][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][1][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][0][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][0][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][2][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][2][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][2] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][0][3] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][2] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][0][3] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines_2.add(joint_line)
        self.wait()
        self.play(ReplacementTransform(surfaces[1][0].copy(), surfaces[2][1]), ReplacementTransform(surfaces[1][1].copy(), surfaces[2][1]), ReplacementTransform(pre_move_lines_2.copy(), bent_plane_joint_lines_2), run_time=3)
        self.add(polygons_22)
        self.remove(bent_plane_joint_lines_2)
        self.add(bent_plane_joint_lines_2)
        self.wait()
        self.play(ReplacementTransform(group_21.copy(), group_31_fakeout), ReplacementTransform(group_22.copy(), group_32_fakeout), run_time=3.0)
        self.wait()
        self.play(FadeOut(group_31_fakeout), FadeOut(group_32_fakeout))
        self.wait()
        relu_intersections_planes_1 = VGroup()
        for neuron_idx in range(2):
            plane = NumberPlane(x_range=(-1, 1, 0.2), y_range=(-1, 1, 0.2), background_line_style={'stroke_color': WHITE, 'stroke_width': 0.5, 'stroke_opacity': 0.9}, faded_line_style={'stroke_color': WHITE, 'stroke_width': 0.0, 'stroke_opacity': 0.0}, axis_config={'stroke_color': WHITE, 'stroke_width': 0.5}).set_width(2).set_height(2)
            plane.shift([3, 0, 1.5 * neuron_idx])
            relu_intersections_planes_1.add(plane)
        self.wait()
        self.play(self.frame.animate.reorient(30, 70, 0, (2.55, 1.16, 0.93), 4.27), group_11.animate.set_opacity(0.2), group_12.animate.set_opacity(0.2), pre_move_lines.animate.set_opacity(0.0), run_time=3)
        self.play(ShowCreation(relu_intersections_planes_1[1]))
        self.wait()
        self.play(self.frame.animate.reorient(32, 83, 0, (2.55, 1.16, 0.93), 4.27), run_time=3)
        self.wait()
        outline = polygons_21[1].copy()
        outline.set_fill(opacity=0)
        outline.set_stroke(width=4, opacity=0.9)
        self.play(ShowCreation(outline, run_time=2))
        outline_2 = polygons_21[3].copy()
        outline_2.set_fill(opacity=0)
        outline_2.set_stroke(width=4, opacity=0.9)
        self.play(ShowCreation(outline_2), FadeOut(outline), run_time=2)
        outline_3 = polygons_21[2].copy()
        outline_3.set_fill(opacity=0)
        outline_3.set_stroke(width=4, opacity=0.9)
        self.play(ShowCreation(outline_3), FadeOut(outline_2), run_time=2)
        self.play(FadeOut(outline_3))
        self.remove(bent_plane_joint_lines)
        self.add(bent_plane_joint_lines)
        self.wait()
        self.play(self.frame.animate.reorient(33, 61, 0, (2.54, 0.96, 0.38), 4.24), run_time=2)
        surfaces[3][0].shift([3, 0, 1.5])
        split_polygons_unraveled = [item for sublist in polygons['1.split_polygons_nested'][0] for item in sublist]
        split_polygons_unraveled_clipped = [item for sublist in polygons['1.split_polygons_nested_clipped'][0] for item in sublist]
        colors_2 = [GREY, BLUE, BLUE, GREEN, GREEN, YELLOW, YELLOW]
        colors_3 = [GREY, BLUE, GREEN, YELLOW]
        polygons_31 = manim_polygons_from_np_list(split_polygons_unraveled, colors=colors_2, viz_scale=viz_scales[2], opacity=0.6)
        polygons_31.shift([3, 0, 1.501])
        polygons_31_clipped = manim_polygons_from_np_list(split_polygons_unraveled_clipped, colors=colors_2, viz_scale=viz_scales[2], opacity=0.6)
        polygons_31_clipped.shift([3, 0, 1.501])
        polygons_31_merged = manim_polygons_from_np_list(polygons['1.split_polygons_merged'][0], colors=colors_3, viz_scale=viz_scales[2], opacity=0.6)
        polygons_31_merged.shift([3, 0, 1.501])
        self.wait()
        self.remove(polygons_21)
        self.add(polygons_31)
        self.remove(bent_plane_joint_lines)
        self.play(ReplacementTransform(polygons_31, polygons_31_clipped), ReplacementTransform(surfaces[2][0], surfaces[3][0]), FadeOut(relu_intersections_planes_1[1]), run_time=3)
        self.remove(polygons_31_clipped)
        self.add(polygons_31_clipped)
        self.wait()
        self.remove(polygons_31_clipped[1], polygons_31_clipped[3], polygons_31_clipped[5])
        self.add(polygons_31_merged[1:])
        self.play(FadeOut(VGroup(*[polygons_31_clipped[i] for i in [0, 2, 4, 6]])), FadeIn(polygons_31_merged[0]))
        self.wait()
        self.play(self.frame.animate.reorient(-1, 38, 0, (3.12, 1.06, 0.18), 4.24), run_time=6)
        self.wait()
        self.play(FadeIn(relu_intersections_planes_1[0]), self.frame.animate.reorient(-132, 58, 0, (2.41, 0.82, 0.12), 2.31), run_time=4)
        self.wait()
        surfaces[3][1].shift([3, 0, 0])
        split_polygons_unraveled_2 = [item for sublist in polygons['1.split_polygons_nested'][1] for item in sublist]
        split_polygons_unraveled_clipped_2 = [item for sublist in polygons['1.split_polygons_nested_clipped'][1] for item in sublist]
        polygons_32 = manim_polygons_from_np_list(split_polygons_unraveled_2, colors=colors_2, viz_scale=viz_scales[2], opacity=0.6)
        polygons_32.shift([3, 0, 0.001])
        polygons_32_clipped = manim_polygons_from_np_list(split_polygons_unraveled_clipped_2, colors=colors_2, viz_scale=viz_scales[2], opacity=0.6)
        polygons_32_clipped.shift([3, 0, 0.001])
        colors_4 = [GREY, GREY, BLUE, GREEN, YELLOW]
        polygons_32_merged = manim_polygons_from_np_list(polygons['1.split_polygons_merged'][1], colors=colors_4, viz_scale=viz_scales[2], opacity=0.6)
        polygons_32_merged.shift([3, 0, 0.001])
        self.wait()
        self.remove(polygons_22)
        self.add(polygons_32)
        self.remove(bent_plane_joint_lines_2)
        self.play(ReplacementTransform(polygons_32, polygons_32_clipped), ReplacementTransform(surfaces[2][1], surfaces[3][1]), FadeOut(relu_intersections_planes_1[0]), run_time=3)
        self.remove(polygons_32_clipped)
        self.add(polygons_32_clipped)
        self.wait()
        self.remove(polygons_32_clipped[1], polygons_32_clipped[3], polygons_32_clipped[5], polygons_32_clipped[0])
        self.add(polygons_32_merged[1:])
        self.play(FadeOut(VGroup(*[polygons_32_clipped[i] for i in [2, 4, 6]])), FadeIn(polygons_32_merged[0]))
        self.wait()
        self.play(self.frame.animate.reorient(0, 57, 0, (2.72, 0.7, -0.61), 6.7), group_11.animate.set_opacity(0.8), group_12.animate.set_opacity(0.8), run_time=6)
        self.wait()
        layer_1_polygons_flat = manim_polygons_from_np_list(polygons['0.new_tiling'], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        layer_1_polygons_flat.shift([0, 0, -1.5])
        colors_5 = [GREY, BLUE, GREEN, YELLOW, PURPLE, ORANGE, PINK, TEAL, MAROON, GREEN_B]
        layer_2_polygons_flat = manim_polygons_from_np_list(polygons['1.new_tiling'], colors=colors_5, viz_scale=viz_scales[2], opacity=0.6)
        layer_2_polygons_flat.shift([3, 0, -1.5])

        def flat_surf_func(u, v):
            return [u, v, 0]
        flat_map_surf = ParametricSurface(flat_surf_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        flat_map = TexturedSurface(flat_map_surf, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
        flat_map.set_shading(0, 0, 0).set_opacity(0.8)
        flat_map.shift([0, 0, -1.5])
        fold_copy_1 = group_11[1].copy()
        fold_copy_2 = group_12[1].copy()
        self.wait()
        self.play(fold_copy_1.animate.shift([0, 0, -3]), fold_copy_2.animate.shift([0, 0, -1.5]), ReplacementTransform(group_11[0].copy(), flat_map), ReplacementTransform(group_12[0].copy(), flat_map), run_time=3)
        self.add(layer_1_polygons_flat)
        self.remove(fold_copy_1)
        self.add(fold_copy_1)
        self.remove(fold_copy_2)
        self.add(fold_copy_2)
        self.remove(flat_map)
        self.wait()
        outline_4 = polygons_31_merged.copy()
        outline_4.set_fill(opacity=0)
        outline_5 = polygons_32_merged.copy()
        outline_5.set_fill(opacity=0)
        polygons_31_merged_flat_arrays = polygons['1.split_polygons_merged'][0]
        for o in polygons_31_merged_flat_arrays:
            o[:, 2] = 0
        polygons_31_merged_flat = manim_polygons_from_np_list(polygons_31_merged_flat_arrays, colors=colors_3, viz_scale=viz_scales[2], opacity=0.6)
        polygons_31_merged_flat.set_fill(opacity=0)
        polygons_31_merged_flat.shift([3, 0, -1.5])
        polygons_32_merged_flat_arrays = polygons['1.split_polygons_merged'][1]
        for o in polygons_32_merged_flat_arrays:
            o[:, 2] = 0
        polygons_32_merged_flat = manim_polygons_from_np_list(polygons_32_merged_flat_arrays, colors=colors_4, viz_scale=viz_scales[2], opacity=0.6)
        polygons_32_merged_flat.set_fill(opacity=0)
        polygons_32_merged_flat.shift([3, 0, -1.5])
        self.wait()
        self.play(ReplacementTransform(outline_4, polygons_31_merged_flat), run_time=4)
        self.play(ReplacementTransform(outline_5, polygons_32_merged_flat), run_time=3)
        self.wait()
        self.play(surfaces[3][1].animate.set_opacity(0.2), polygons_32_merged.animate.set_opacity(0.2), layer_1_polygons_flat.animate.set_opacity(0.2), self.frame.animate.reorient(0, 44, 0, (3.15, -0.12, -1.73), 3.42), run_time=4)
        self.wait()
        self.play(ShowCreation(layer_2_polygons_flat), run_time=3)
        self.wait()
        self.play(self.frame.animate.reorient(-1, 68, 0, (3.09, 0.76, -0.31), 6.95), surfaces[3][1].animate.set_opacity(0.6), polygons_32_merged.animate.set_opacity(0.8), layer_1_polygons_flat.animate.set_opacity(0.25), layer_2_polygons_flat.animate.set_opacity(0.25), polygons_31_merged_flat.animate.set_opacity(0.0), polygons_32_merged_flat.animate.set_opacity(0.0), run_time=4)
        self.wait()
        outline_6 = polygons_31_merged.copy()
        outline_6.set_fill(opacity=0)
        outline_7 = polygons_32_merged.copy()
        outline_7.set_fill(opacity=0)
        final_layer_middle_tiling_arrays_1 = process_with_layers(model.model, polygons_31_merged_flat_arrays)
        final_layer_middle_tiling_1 = manim_polygons_from_np_list(final_layer_middle_tiling_arrays_1[0], colors=colors_3, viz_scale=viz_scales[4], opacity=0.6)
        final_layer_middle_tiling_1.set_fill(opacity=0)
        final_layer_middle_tiling_1.shift([6, 0, 1.5])
        final_layer_middle_tiling_arrays_2 = process_with_layers(model.model, polygons_32_merged_flat_arrays)
        final_layer_middle_tiling_2 = manim_polygons_from_np_list(final_layer_middle_tiling_arrays_2[0], colors=colors_4, viz_scale=viz_scales[4], opacity=0.6)
        final_layer_middle_tiling_2.set_fill(opacity=0)
        final_layer_middle_tiling_2.shift([6, 0, 1.5])
        polygons_41 = manim_polygons_from_np_list(polygons['2.linear_out'][0], colors=colors_5, viz_scale=viz_scales[4], opacity=0.6)
        polygons_41.shift([6, 0, 1.501])
        polygons_41_outline = polygons_41.copy()
        polygons_41_outline.set_fill(opacity=0)
        surfaces[4][0].shift([6, 0, 1.5])
        self.wait()
        self.play(ReplacementTransform(outline_6.copy(), final_layer_middle_tiling_1), ReplacementTransform(outline_7.copy(), final_layer_middle_tiling_2), run_time=3)
        self.remove(final_layer_middle_tiling_1, final_layer_middle_tiling_2)
        self.add(polygons_41_outline)
        self.wait()
        self.play(ReplacementTransform(layer_2_polygons_flat.copy(), polygons_41), run_time=3)
        self.add(surfaces[4][0])
        self.remove(polygons_41_outline)
        self.remove(polygons_41)
        self.add(polygons_41)
        self.wait()
        final_layer_middle_tiling_arrays_1b = process_with_layers(model.model, polygons_31_merged_flat_arrays)
        final_layer_middle_tiling_1b = manim_polygons_from_np_list(final_layer_middle_tiling_arrays_1b[1], colors=colors_3, viz_scale=viz_scales[4], opacity=0.6)
        final_layer_middle_tiling_1b.set_fill(opacity=0)
        final_layer_middle_tiling_1b.shift([6, 0, 0.2])
        final_layer_middle_tiling_arrays_2b = process_with_layers(model.model, polygons_32_merged_flat_arrays)
        final_layer_middle_tiling_2b = manim_polygons_from_np_list(final_layer_middle_tiling_arrays_2b[1], colors=colors_4, viz_scale=viz_scales[4], opacity=0.6)
        final_layer_middle_tiling_2b.set_fill(opacity=0)
        final_layer_middle_tiling_2b.shift([6, 0, 0.2])
        polygons_41b = manim_polygons_from_np_list(polygons['2.linear_out'][1], colors=colors_5, viz_scale=viz_scales[4], opacity=0.6)
        polygons_41b.shift([6, 0, 0.201])
        polygons_41_outline_b = polygons_41b.copy()
        polygons_41_outline_b.set_fill(opacity=0)
        surfaces[4][1].shift([6, 0, 0.2])
        self.wait()
        self.play(ReplacementTransform(outline_6, final_layer_middle_tiling_1b), ReplacementTransform(outline_7, final_layer_middle_tiling_2b), run_time=3)
        self.remove(final_layer_middle_tiling_1b, final_layer_middle_tiling_2b)
        self.add(polygons_41_outline_b)
        self.wait()
        self.play(ReplacementTransform(layer_2_polygons_flat.copy(), polygons_41b), run_time=3)
        self.add(surfaces[4][1])
        self.remove(polygons_41_outline_b)
        self.remove(polygons_41b)
        self.add(polygons_41b)
        self.wait()
        self.play(self.frame.animate.reorient(-29, 48, 0, (6.05, 0.45, -0.12), 6.53), run_time=4)
        self.wait()
        polygons_51 = polygons_41.copy()
        polygons_52 = polygons_41b.copy()
        surface_51 = surfaces[4][0].copy()
        surface_52 = surfaces[4][1].copy()
        polygons_51.shift([3, 0, -0.7])
        polygons_52.shift([3, 0, 0.6])
        surface_51.shift([3, 0, -0.7])
        surface_52.shift([3, 0, 0.6])
        polygons_51.set_color(BLUE)
        polygons_52.set_color(YELLOW)
        lines = VGroup()
        for loop in intersection_lines:
            loop = loop * np.array([1, 1, viz_scales[2]])
            line = VMobject()
            line.set_points_as_corners(loop)
            line.set_stroke(color='#FF00FF', width=5)
            lines.add(line)
        lines.shift([9, 0, 0.8])
        surface_51.set_opacity(0.2)
        surface_52.set_opacity(0.9)
        polygons_51.set_opacity(0.4)
        polygons_52.set_opacity(0.5)
        self.wait()
        self.play(self.frame.animate.reorient(-11, 31, 0, (7.76, 0.49, 0.19), 5.53), ReplacementTransform(surfaces[4][0].copy(), surface_51), ReplacementTransform(surfaces[4][1].copy(), surface_52), ReplacementTransform(polygons_41.copy(), polygons_51), ReplacementTransform(polygons_41b.copy(), polygons_52), run_time=4)
        self.remove(polygons_51)
        self.add(polygons_51)
        self.remove(polygons_52)
        self.add(polygons_52)
        self.wait()
        self.play(ShowCreation(lines), run_time=2)
        self.wait()
        top_polygons_vgroup_flat = VGroup()
        for j, p in enumerate(my_top_polygons):
            if len(p) < 3:
                continue
            if my_indicator[j]:
                color = YELLOW
            else:
                color = BLUE
            p_scaled = copy.deepcopy(p)
            p_scaled[:, 2] = 0
            poly_3d = Polygon(*p_scaled, fill_color=color, fill_opacity=0.4, stroke_color=color, stroke_width=2)
            poly_3d.set_opacity(0.5)
            poly_3d.shift([9, 0, -1.499])
            top_polygons_vgroup_flat.add(poly_3d)
        polygon_arrays_1_flat = copy.deepcopy(polygons['2.linear_out'][0])
        for p in polygon_arrays_1_flat:
            p[:, 2] = 0
        polygon_arrays_2_flat = copy.deepcopy(polygons['2.linear_out'][1])
        for p in polygon_arrays_2_flat:
            p[:, 2] = 0
        polygons_51_flat = manim_polygons_from_np_list(polygon_arrays_1_flat, colors=colors, viz_scale=viz_scales[2])
        polygons_51_flat.shift([9, 0, -1.499])
        polygons_52_flat = manim_polygons_from_np_list(polygon_arrays_2_flat, colors=colors, viz_scale=viz_scales[2])
        polygons_52_flat.shift([9, 0, -1.499])
        polygons_51_flat.set_color(YELLOW)
        polygons_51_flat.set_color(BLUE)
        polygons_51_flat.set_opacity(0.5)
        polygons_52_flat.set_opacity(0.5)
        flat_map_surf = ParametricSurface(flat_surf_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        flat_map_2 = TexturedSurface(flat_map_surf, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
        flat_map_2.set_shading(0, 0, 0).set_opacity(0.8)
        flat_map_2.shift([9, 0, -1.5])
        lines_flat = VGroup()
        for loop in intersection_lines:
            loop[:, 2] = 0
            line = VMobject()
            line.set_points_as_corners(loop)
            line.set_stroke(color='#FF00FF', width=4)
            lines_flat.add(line)
        lines_flat.shift([9, 0, -1.5])
        polygons_51_copy = polygons_51.copy()
        polygons_52_copy = polygons_52.copy()
        surface_51_copy = surface_51.copy()
        polygons_51_copy.set_opacity(0.3)
        polygons_52_copy.set_opacity(0.3)
        surface_51_copy.set_opacity(0.3)
        self.wait()
        self.play(ReplacementTransform(polygons_51_copy, polygons_51_flat), ReplacementTransform(polygons_52_copy, polygons_52_flat), ReplacementTransform(lines.copy(), lines_flat), self.frame.animate.reorient(0, 39, 0, (9.07, -0.55, -0.82), 3.8), run_time=3)
        self.add(flat_map_2)
        self.remove(polygons_51_flat, polygons_52_flat)
        self.add(top_polygons_vgroup_flat)
        self.remove(lines_flat)
        self.add(lines_flat)
        self.wait()
        self.play(self.frame.animate.reorient(0, 57, 0, (4.6, -0.08, -0.8), 8.34), layer_1_polygons_flat.animate.set_opacity(0.55), layer_2_polygons_flat.animate.set_opacity(0.55), run_time=6)
        self.wait()
        layer_2_polygons_flat.shift([1.7, 0, 0])
        flat_map_2.shift([-1.7, 0, 0])
        top_polygons_vgroup_flat.shift([-1.7, 0, 0])
        lines_flat.shift([-1.7, 0, 0])
        self.clear()
        self.frame.reorient(0, 0, 0, (5.78, -1.16, 0.0), 4.36)
        self.add(flat_map_2)
        self.add(top_polygons_vgroup_flat)
        self.add(lines_flat)
        self.add(layer_2_polygons_flat)
        self.wait()
        self.wait(20)
        self.embed()

class p52b(InteractiveScene):

    def construct(self):
        w1 = np.array([[-1.8741, 2.12215], [-2.39381, -1.24014], [-0.940185, 1.40271], [2.04548, 0.489156]], dtype=np.float32)
        b1 = np.array([-0.00892048, -1.32954, 1.71349, 0.940607], dtype=np.float32)
        w2 = np.array([[2.56674, 2.26244, -1.40175, 0.737865], [-2.58904, -3.0681, 1.08007, -1.32219]], dtype=np.float32)
        b2 = np.array([-0.852075, 0.492386], dtype=np.float32)
        model = BaarleNet([4])
        with torch.no_grad():
            model.model[0].weight.copy_(torch.from_numpy(w1))
            model.model[0].bias.copy_(torch.from_numpy(b1))
            model.model[2].weight.copy_(torch.from_numpy(w2))
            model.model[2].bias.copy_(torch.from_numpy(b2))
        viz_scales = [0.15, 0.15, 0.13]
        num_neurons = [4, 4, 2]
        surfaces = []
        surface_funcs = []
        for layer_idx in range(len(model.model)):
            s = Group()
            surface_funcs.append([])
            for neuron_idx in range(num_neurons[layer_idx]):
                surface_func = partial(surface_func_from_model, model=model, layer_idx=layer_idx, neuron_idx=neuron_idx, viz_scale=viz_scales[layer_idx])
                bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
                ts = TexturedSurface(bent_surface, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
                ts.set_shading(0, 0, 0).set_opacity(0.8)
                s.add(ts)
                surface_funcs[-1].append(surface_func)
            surfaces.append(s)
        polygons = {}
        polygons['-1.new_tiling'] = [np.array([[-1.0, -1, 0], [-1, 1, 0], [1, 1, 0], [1, -1, 0]])]
        for layer_id in range(len(model.model) // 2):
            polygons[str(layer_id) + '.linear_out'] = process_with_layers(model.model[:2 * layer_id + 1], polygons[str(layer_id - 1) + '.new_tiling'])
            polygons[str(layer_id) + '.split_polygons_nested'] = split_polygons_with_relu_simple(polygons[str(layer_id) + '.linear_out'])
            polygons[str(layer_id) + '.split_polygons_nested_clipped'] = clip_polygons(polygons[str(layer_id) + '.split_polygons_nested'])
            polygons[str(layer_id) + '.split_polygons_merged'] = merge_zero_regions(polygons[str(layer_id) + '.split_polygons_nested_clipped'])
            polygons[str(layer_id) + '.new_tiling'] = recompute_tiling_general(polygons[str(layer_id) + '.split_polygons_merged'])
            print('Retiled plane into ', str(len(polygons[str(layer_id) + '.new_tiling'])), ' polygons.')
        polygons[str(layer_id + 1) + '.linear_out'] = process_with_layers(model.model, polygons[str(layer_id) + '.new_tiling'])
        intersection_lines, new_2d_tiling, upper_polytope, indicator = intersect_polytopes(*polygons[str(layer_id + 1) + '.linear_out'])
        my_indicator, my_top_polygons = compute_top_polytope(model, new_2d_tiling)
        joint_points_11 = get_relu_joint(w1[0, 0], w1[0, 1], b1[0], extent=1)
        group_11 = Group(surfaces[1][0])
        if len(joint_points_11) > 0:
            joint_line_11 = line_from_joint_points_1(joint_points_11).set_opacity(0.9)
            group_11.add(joint_line_11)
        group_12 = Group(surfaces[1][1])
        joint_points_12 = get_relu_joint(w1[1, 0], w1[1, 1], b1[1], extent=1)
        if len(joint_points_12) > 0:
            joint_line_12 = line_from_joint_points_1(joint_points_12).set_opacity(0.9)
            group_12.add(joint_line_12)
        group_13 = Group(surfaces[1][2])
        joint_points_13 = get_relu_joint(w1[2, 0], w1[2, 1], b1[2], extent=1)
        if len(joint_points_13) > 0:
            joint_line_13 = line_from_joint_points_1(joint_points_13).set_opacity(0.9)
            group_13.add(joint_line_13)
        group_14 = Group(surfaces[1][3])
        joint_points_14 = get_relu_joint(w1[3, 0], w1[3, 1], b1[3], extent=1)
        if len(joint_points_14) > 0:
            joint_line_14 = line_from_joint_points_1(joint_points_14).set_opacity(0.9)
            group_14.add(joint_line_14)
        group_11.shift([0, 0, 3.0])
        group_12.shift([0, 0, 2.0])
        group_13.shift([0, 0, 1.0])
        polygons_21 = manim_polygons_from_np_list(polygons['1.linear_out'][0], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_21.shift([0, 0, 0.001])
        polygons_22 = manim_polygons_from_np_list(polygons['1.linear_out'][1], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_22.shift([0, 0, 0.001])
        group_21 = Group(surfaces[2][0], polygons_21)
        group_22 = Group(surfaces[2][1], polygons_22)
        group_21.shift([3.0, 0, 2.4])
        group_22.shift([3.0, 0, 1.1])
        group_21.set_opacity(0.5)
        group_22.set_opacity(0.5)
        group_31 = group_21.copy()
        group_31[1].set_color(BLUE)
        group_31.shift([3, 0, -0.65])
        group_32 = group_22.copy()
        group_32[1].set_color(YELLOW)
        group_32.shift([3, 0, 0.65])
        loops = order_closed_loops_with_closure(intersection_lines)
        lines = VGroup()
        for loop in loops:
            loop = loop * np.array([1, 1, viz_scales[2]])
            line = VMobject()
            line.set_points_as_corners(loop)
            line.set_stroke(color='#FF00FF', width=4)
            lines.add(line)
        lines.shift([6, 0, 1.1 + 0.65])
        group_31[0].set_opacity(0.9)
        group_32[0].set_opacity(0.9)
        group_31[1].set_opacity(0.4)
        group_32[1].set_opacity(0.4)
        layer_1_polygons_flat = manim_polygons_from_np_list(polygons['0.new_tiling'], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        layer_1_polygons_flat.shift([0, 0, -1.0])
        top_polygons_vgroup_flat = VGroup()
        for j, p in enumerate(my_top_polygons):
            if len(p) < 3:
                continue
            if my_indicator[j]:
                color = YELLOW
            else:
                color = BLUE
            p_scaled = copy.deepcopy(p)
            p_scaled[:, 2] = 0
            poly_3d = Polygon(*p_scaled, fill_color=color, fill_opacity=0.4, stroke_color=color, stroke_width=2)
            poly_3d.set_opacity(0.5)
            poly_3d.shift([6, 0, -0.99])
            top_polygons_vgroup_flat.add(poly_3d)

        def flat_surf_func(u, v):
            return [u, v, 0]
        flat_map_surf = ParametricSurface(flat_surf_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        flat_map_2 = TexturedSurface(flat_map_surf, graphics_dir + '/baarle_hertog_maps/baarle_hertog_maps-17.png')
        flat_map_2.set_shading(0, 0, 0).set_opacity(0.8)
        flat_map_2.shift([6, 0, -1.0])
        lines_flat = VGroup()
        for loop in intersection_lines:
            loop[:, 2] = 0
            line = VMobject()
            line.set_points_as_corners(loop)
            line.set_stroke(color='#FF00FF', width=4)
            lines_flat.add(line)
        lines_flat.shift([6, 0, -1.0])
        self.frame.reorient(0, 32, 0, (2.97, -0.05, 0.59), 7.12)
        self.add(group_11, group_12, group_13, group_14)
        self.add(group_21, group_22)
        self.add(group_31, group_32, lines)
        self.add(layer_1_polygons_flat)
        self.add(flat_map_2)
        self.add(top_polygons_vgroup_flat)
        self.add(lines_flat)
        self.wait()
        self.play(self.frame.animate.reorient(-1, 56, 0, (2.97, -0.05, 0.59), 7.12), run_time=8)
        self.wait()
        self.play(FadeOut(group_11), FadeOut(group_12), FadeOut(group_13), FadeOut(group_14), FadeOut(group_21), FadeOut(group_22), FadeOut(group_31), FadeOut(group_32), FadeOut(lines), layer_1_polygons_flat.animate.shift([1.7, 0, 0]), top_polygons_vgroup_flat.animate.shift([-1.7, 0, 0]), lines_flat.animate.shift([-1.7, 0, 0]), flat_map_2.animate.shift([-1.7, 0, 0]), self.frame.animate.reorient(0, 0, 0, (3.06, -1.13, 0.0), 4.36), run_time=6, rate_func=linear)
        self.wait()
        self.wait(20)
        self.embed()