from functools import partial
import sys
sys.path.append('_2025/backprop_3')
from geometric_dl_utils import *
from plane_folding_utils import *
from geometric_dl_utils_simplified import *
from polytope_intersection_utils import intersect_polytopes
from manimlib import *
CHILL_BROWN = '#948979'
YELLOW = '#ffd35a'
YELLOW_FADE = '#7f6a2d'
BLUE = '#65c8d0'
GREEN = '#6e9671'
CHILL_GREEN = '#6c946f'
CHILL_BLUE = '#3d5c6f'
FRESH_TAN = '#dfd0b9'
CYAN = '#00FFFF'
graphics_dir = '/Users/stephen/Stephencwelch Dropbox/welch_labs/ai_book/4_deep_learning/graphics/'
map_filename = 'baarle_hertog_maps-13.png'
colors = [GREY, BLUE, GREEN, YELLOW, PURPLE, ORANGE, PINK, TEAL]

class p47d(InteractiveScene):

    def construct(self):
        map_img = ImageMobject(graphics_dir + '/baarle_hertog_maps/' + map_filename)
        map_img.set_height(2)
        map_img.set_width(2)
        map_img.move_to(ORIGIN)
        model_path = '_2025/backprop_3/models/2_2_1.pth'
        model = BaarleNet([2, 2])
        model.load_state_dict(torch.load(model_path))
        viz_scales = [0.25, 0.25, 0.3, 0.3, 0.15]
        num_neurons = [2, 2, 2, 2, 2]
        w1 = model.model[0].weight.detach().numpy()
        b1 = model.model[0].bias.detach().numpy()
        w2 = model.model[2].weight.detach().numpy()
        b2 = model.model[2].bias.detach().numpy()
        surfaces = []
        surface_funcs = []
        for layer_idx in range(len(model.model)):
            s = Group()
            surface_funcs.append([])
            for neuron_idx in range(num_neurons[layer_idx]):
                surface_func = partial(surface_func_from_model, model=model, layer_idx=layer_idx, neuron_idx=neuron_idx, viz_scale=viz_scales[layer_idx])
                bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
                ts = TexturedSurface(bent_surface, graphics_dir + '/baarle_hertog_maps/' + map_filename)
                ts.set_shading(0, 0, 0).set_opacity(0.8)
                s.add(ts)
                surface_funcs[-1].append(surface_func)
            surfaces.append(s)
        polygons = {}
        polygons['-1.new_tiling'] = [np.array([[-1.0, -1, 0], [-1, 1, 0], [1, 1, 0], [1, -1, 0]])]
        for layer_id in range(len(model.model) // 2):
            polygons[str(layer_id) + '.linear_out'] = process_with_layers(model.model[:2 * layer_id + 1], polygons[str(layer_id - 1) + '.new_tiling'])
            polygons[str(layer_id) + '.split_polygons_nested'] = split_polygons_with_relu_simple(polygons[str(layer_id) + '.linear_out'])
            polygons[str(layer_id) + '.split_polygons_nested_clipped'] = clip_polygons(polygons[str(layer_id) + '.split_polygons_nested'])
            polygons[str(layer_id) + '.split_polygons_merged'] = merge_zero_regions(polygons[str(layer_id) + '.split_polygons_nested_clipped'])
            polygons[str(layer_id) + '.new_tiling'] = recompute_tiling_general(polygons[str(layer_id) + '.split_polygons_merged'])
            print('Retiled plane into ', str(len(polygons[str(layer_id) + '.new_tiling'])), ' polygons.')
        polygons[str(layer_id + 1) + '.linear_out'] = process_with_layers(model.model, polygons[str(layer_id) + '.new_tiling'])
        intersection_lines, new_2d_tiling, upper_polytope, indicator = intersect_polytopes(*polygons[str(layer_id + 1) + '.linear_out'])
        my_indicator, my_top_polygons = compute_top_polytope(model, new_2d_tiling)
        joint_points_11 = get_relu_joint(w1[0, 0], w1[0, 1], b1[0], extent=1)
        group_11 = Group(surfaces[1][0])
        if len(joint_points_11) > 0:
            joint_line_11 = line_from_joint_points_1(joint_points_11).set_opacity(0.9)
            group_11.add(joint_line_11)
        group_12 = Group(surfaces[1][1])
        joint_points_12 = get_relu_joint(w1[1, 0], w1[1, 1], b1[1], extent=1)
        if len(joint_points_12) > 0:
            joint_line_12 = line_from_joint_points_1(joint_points_12).set_opacity(0.9)
            group_12.add(joint_line_12)
        group_11.shift([0, 0, 1.5])
        polygons_21 = manim_polygons_from_np_list(polygons['1.linear_out'][0], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_21.shift([0, 0, 0.001])
        polygons_22 = manim_polygons_from_np_list(polygons['1.linear_out'][1], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_22.shift([0, 0, 0.001])
        group_21 = Group(surfaces[2][0], polygons_21)
        group_22 = Group(surfaces[2][1], polygons_22)
        group_21.shift([3.0, 0, 1.5])
        group_22.shift([3.0, 0, 0])
        group_21.set_opacity(0.5)
        group_22.set_opacity(0.5)
        group_31_fakeout = group_21.copy()
        group_31_fakeout[1].set_color(BLUE)
        group_31_fakeout.shift([3, 0, -0.75])
        group_32_fakeout = group_22.copy()
        group_32_fakeout[1].set_color(YELLOW)
        group_32_fakeout.shift([3, 0, 0.75])
        group_31_fakeout[0].set_opacity(0.9)
        group_32_fakeout[0].set_opacity(0.9)
        group_31_fakeout[1].set_opacity(0.4)
        group_32_fakeout[1].set_opacity(0.4)
        bent_plane_joint_lines = VGroup()
        pre_move_lines = VGroup()
        line_start = polygons['1.linear_out'][0][1][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][1][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][1][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][1][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][0][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][0][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][2][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][2][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][2] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][0][0][3] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 1.5])
        bent_plane_joint_lines.add(joint_line)
        line_start = polygons['1.linear_out'][0][0][2] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][0][0][3] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines.add(joint_line)
        self.frame.reorient(-2, 46, 0, (3.11, 0.22, -0.73), 6.89)
        bent_plane_joint_lines_2 = VGroup()
        pre_move_lines_2 = VGroup()
        line_start = polygons['1.linear_out'][1][1][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][1][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][1][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][1][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][3] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][0][0] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][3] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][0][0] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([0, 0, 1.5])
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][0] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][2][1] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][2][0] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][2][1] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][2] * np.array([1, 1, viz_scales[2]])
        line_end = polygons['1.linear_out'][1][0][3] * np.array([1, 1, viz_scales[2]])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        joint_line.shift([3, 0, 0])
        bent_plane_joint_lines_2.add(joint_line)
        line_start = polygons['1.linear_out'][1][0][2] * np.array([1, 1, 0])
        line_end = polygons['1.linear_out'][1][0][3] * np.array([1, 1, 0])
        joint_line = DashedLine(start=line_start, end=line_end, color=WHITE, stroke_width=3, dash_length=0.05)
        pre_move_lines_2.add(joint_line)
        relu_intersections_planes_1 = VGroup()
        for neuron_idx in range(2):
            plane = NumberPlane(x_range=(-1, 1, 0.2), y_range=(-1, 1, 0.2), background_line_style={'stroke_color': BLACK, 'stroke_width': 1.2, 'stroke_opacity': 0.9}, faded_line_style={'stroke_color': BLACK, 'stroke_width': 0.0, 'stroke_opacity': 0.0}, axis_config={'stroke_color': BLACK, 'stroke_width': 1.2}).set_width(2).set_height(2)
            plane.shift([3, 0, 1.5 * neuron_idx])
            relu_intersections_planes_1.add(plane)
        outline = polygons_21[1].copy()
        outline.set_fill(opacity=0)
        outline.set_stroke(width=4, opacity=0.9)
        outline_2 = polygons_21[3].copy()
        outline_2.set_fill(opacity=0)
        outline_2.set_stroke(width=4, opacity=0.9)
        outline_3 = polygons_21[2].copy()
        outline_3.set_fill(opacity=0)
        outline_3.set_stroke(width=4, opacity=0.9)
        surfaces[3][0].shift([3, 0, 1.5])
        split_polygons_unraveled = [item for sublist in polygons['1.split_polygons_nested'][0] for item in sublist]
        split_polygons_unraveled_clipped = [item for sublist in polygons['1.split_polygons_nested_clipped'][0] for item in sublist]
        colors_2 = [GREY, BLUE, BLUE, GREEN, GREEN, YELLOW, YELLOW]
        colors_3 = [GREY, BLUE, GREEN, YELLOW]
        polygons_31 = manim_polygons_from_np_list(split_polygons_unraveled, colors=colors_2, viz_scale=viz_scales[2], opacity=0.6)
        polygons_31.shift([3, 0, 1.501])
        polygons_31_clipped = manim_polygons_from_np_list(split_polygons_unraveled_clipped, colors=colors_2, viz_scale=viz_scales[2], opacity=0.6)
        polygons_31_clipped.shift([3, 0, 1.501])
        polygons_31_merged = manim_polygons_from_np_list(polygons['1.split_polygons_merged'][0], colors=colors_3, viz_scale=viz_scales[2], opacity=0.6)
        polygons_31_merged.shift([3, 0, 1.501])
        surfaces[3][1].shift([3, 0, 0])
        split_polygons_unraveled_2 = [item for sublist in polygons['1.split_polygons_nested'][1] for item in sublist]
        split_polygons_unraveled_clipped_2 = [item for sublist in polygons['1.split_polygons_nested_clipped'][1] for item in sublist]
        polygons_32 = manim_polygons_from_np_list(split_polygons_unraveled_2, colors=colors_2, viz_scale=viz_scales[2], opacity=0.6)
        polygons_32.shift([3, 0, 0.001])
        polygons_32_clipped = manim_polygons_from_np_list(split_polygons_unraveled_clipped_2, colors=colors_2, viz_scale=viz_scales[2], opacity=0.6)
        polygons_32_clipped.shift([3, 0, 0.001])
        colors_4 = [GREY, GREY, BLUE, GREEN, YELLOW]
        polygons_32_merged = manim_polygons_from_np_list(polygons['1.split_polygons_merged'][1], colors=colors_4, viz_scale=viz_scales[2], opacity=0.6)
        polygons_32_merged.shift([3, 0, 0.001])
        self.wait()
        group_11[0].move_to(ORIGIN)
        self.frame.reorient(0, 58, 0, (-0.0, -0.13, -0.16), 2.74)
        self.add(group_11[0])
        self.wait()
        self.remove(group_11[0])
        group_12[0].move_to(ORIGIN)
        self.add(group_12[0])
        self.wait()
        self.remove(group_12[0])
        new_group_1 = Group(surfaces[2][0], polygons_21, relu_intersections_planes_1[1])
        new_group_1.move_to(ORIGIN)
        self.add(new_group_1[:2])
        self.wait()
        self.add(new_group_1[2])
        self.wait()
        self.frame.reorient(44, 88, 0, (-0.0, -0.13, -0.16), 2.74)
        self.wait()
        self.remove(new_group_1[2])
        self.frame.reorient(0, 58, 0, (-0.0, -0.13, -0.16), 2.74)
        self.wait()
        self.remove(new_group_1)
        new_group_2 = Group(surfaces[2][1], polygons_22, relu_intersections_planes_1[0])
        new_group_2.move_to(ORIGIN)
        self.frame.reorient(1, 45, 0, (-0.0, -0.13, -0.16), 2.74)
        self.add(new_group_2[:2])
        self.wait()
        self.add(new_group_2[2])
        self.wait()
        self.frame.reorient(-123, 65, 0, (0.02, -0.05, -0.24), 2.74)
        self.wait()
        self.remove(new_group_2[2])
        self.frame.reorient(1, 45, 0, (-0.0, -0.13, -0.16), 2.74)
        self.wait()
        self.remove(new_group_2)
        self.frame.reorient(0, 58, 0, (-0.0, -0.13, -0.16), 2.74)
        self.wait()
        new_group_3 = Group(surfaces[3][0], polygons_31_clipped, polygons_31_merged)
        new_group_3.move_to(ORIGIN)
        self.add(surfaces[3][0])
        self.add(polygons_31_clipped)
        self.wait()
        self.remove(polygons_31_clipped)
        self.add(polygons_31_merged)
        self.wait()
        self.remove(new_group_3)
        self.wait()
        new_group_4 = Group(surfaces[3][1], polygons_32_clipped, polygons_32_merged)
        new_group_4.move_to(ORIGIN)
        self.frame.reorient(0, 50, 0, (-0.02, -0.15, -0.19), 2.74)
        self.add(surfaces[3][1])
        self.add(polygons_32_clipped)
        self.wait()
        self.remove(polygons_32_clipped)
        self.add(polygons_32_merged)
        self.wait()
        self.remove(new_group_4)
        self.wait()
        self.wait(20)
        self.embed()

class p52b(InteractiveScene):

    def construct(self):
        w1 = np.array([[-1.8741, 2.12215], [-2.39381, -1.24014], [-0.940185, 1.40271], [2.04548, 0.489156]], dtype=np.float32)
        b1 = np.array([-0.00892048, -1.32954, 1.71349, 0.940607], dtype=np.float32)
        w2 = np.array([[2.56674, 2.26244, -1.40175, 0.737865], [-2.58904, -3.0681, 1.08007, -1.32219]], dtype=np.float32)
        b2 = np.array([-0.852075, 0.492386], dtype=np.float32)
        model = BaarleNet([4])
        with torch.no_grad():
            model.model[0].weight.copy_(torch.from_numpy(w1))
            model.model[0].bias.copy_(torch.from_numpy(b1))
            model.model[2].weight.copy_(torch.from_numpy(w2))
            model.model[2].bias.copy_(torch.from_numpy(b2))
        viz_scales = [0.15, 0.15, 0.13]
        num_neurons = [4, 4, 2]
        surfaces = []
        surface_funcs = []
        for layer_idx in range(len(model.model)):
            s = Group()
            surface_funcs.append([])
            for neuron_idx in range(num_neurons[layer_idx]):
                surface_func = partial(surface_func_from_model, model=model, layer_idx=layer_idx, neuron_idx=neuron_idx, viz_scale=viz_scales[layer_idx])
                bent_surface = ParametricSurface(surface_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
                ts = TexturedSurface(bent_surface, graphics_dir + '/baarle_hertog_maps/' + map_filename)
                ts.set_shading(0, 0, 0).set_opacity(0.8)
                s.add(ts)
                surface_funcs[-1].append(surface_func)
            surfaces.append(s)
        polygons = {}
        polygons['-1.new_tiling'] = [np.array([[-1.0, -1, 0], [-1, 1, 0], [1, 1, 0], [1, -1, 0]])]
        for layer_id in range(len(model.model) // 2):
            polygons[str(layer_id) + '.linear_out'] = process_with_layers(model.model[:2 * layer_id + 1], polygons[str(layer_id - 1) + '.new_tiling'])
            polygons[str(layer_id) + '.split_polygons_nested'] = split_polygons_with_relu_simple(polygons[str(layer_id) + '.linear_out'])
            polygons[str(layer_id) + '.split_polygons_nested_clipped'] = clip_polygons(polygons[str(layer_id) + '.split_polygons_nested'])
            polygons[str(layer_id) + '.split_polygons_merged'] = merge_zero_regions(polygons[str(layer_id) + '.split_polygons_nested_clipped'])
            polygons[str(layer_id) + '.new_tiling'] = recompute_tiling_general(polygons[str(layer_id) + '.split_polygons_merged'])
            print('Retiled plane into ', str(len(polygons[str(layer_id) + '.new_tiling'])), ' polygons.')
        polygons[str(layer_id + 1) + '.linear_out'] = process_with_layers(model.model, polygons[str(layer_id) + '.new_tiling'])
        intersection_lines, new_2d_tiling, upper_polytope, indicator = intersect_polytopes(*polygons[str(layer_id + 1) + '.linear_out'])
        my_indicator, my_top_polygons = compute_top_polytope(model, new_2d_tiling)
        joint_points_11 = get_relu_joint(w1[0, 0], w1[0, 1], b1[0], extent=1)
        group_11 = Group(surfaces[1][0])
        if len(joint_points_11) > 0:
            joint_line_11 = line_from_joint_points_1(joint_points_11).set_opacity(0.9)
            group_11.add(joint_line_11)
        group_12 = Group(surfaces[1][1])
        joint_points_12 = get_relu_joint(w1[1, 0], w1[1, 1], b1[1], extent=1)
        if len(joint_points_12) > 0:
            joint_line_12 = line_from_joint_points_1(joint_points_12).set_opacity(0.9)
            group_12.add(joint_line_12)
        group_13 = Group(surfaces[1][2])
        joint_points_13 = get_relu_joint(w1[2, 0], w1[2, 1], b1[2], extent=1)
        if len(joint_points_13) > 0:
            joint_line_13 = line_from_joint_points_1(joint_points_13).set_opacity(0.9)
            group_13.add(joint_line_13)
        group_14 = Group(surfaces[1][3])
        joint_points_14 = get_relu_joint(w1[3, 0], w1[3, 1], b1[3], extent=1)
        if len(joint_points_14) > 0:
            joint_line_14 = line_from_joint_points_1(joint_points_14).set_opacity(0.9)
            group_14.add(joint_line_14)
        group_11.shift([0, 0, 3.0])
        group_12.shift([0, 0, 2.0])
        group_13.shift([0, 0, 1.0])
        polygons_21 = manim_polygons_from_np_list(polygons['1.linear_out'][0], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_21.shift([0, 0, 0.001])
        polygons_22 = manim_polygons_from_np_list(polygons['1.linear_out'][1], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        polygons_22.shift([0, 0, 0.001])
        group_21 = Group(surfaces[2][0], polygons_21)
        group_22 = Group(surfaces[2][1], polygons_22)
        group_21.shift([3.0, 0, 2.4])
        group_22.shift([3.0, 0, 1.1])
        group_21.set_opacity(0.5)
        group_22.set_opacity(0.5)
        group_31 = group_21.copy()
        group_31[1].set_color(BLUE)
        group_31.shift([3, 0, -0.65])
        group_32 = group_22.copy()
        group_32[1].set_color(YELLOW)
        group_32.shift([3, 0, 0.65])
        loops = order_closed_loops_with_closure(intersection_lines)
        lines = VGroup()
        for loop in loops:
            loop = loop * np.array([1, 1, viz_scales[2]])
            line = VMobject()
            line.set_points_as_corners(loop)
            line.set_stroke(color='#FF00FF', width=4)
            lines.add(line)
        lines.shift([6, 0, 1.1 + 0.65])
        group_31[0].set_opacity(0.9)
        group_32[0].set_opacity(0.9)
        group_31[1].set_opacity(0.4)
        group_32[1].set_opacity(0.4)
        layer_1_polygons_flat = manim_polygons_from_np_list(polygons['0.new_tiling'], colors=colors, viz_scale=viz_scales[2], opacity=0.6)
        layer_1_polygons_flat.shift([0, 0, -1.0])
        top_polygons_vgroup_flat = VGroup()
        for j, p in enumerate(my_top_polygons):
            if len(p) < 3:
                continue
            if my_indicator[j]:
                color = YELLOW
            else:
                color = BLUE
            p_scaled = copy.deepcopy(p)
            p_scaled[:, 2] = 0
            poly_3d = Polygon(*p_scaled, fill_color=color, fill_opacity=0.4, stroke_color=color, stroke_width=2)
            poly_3d.set_opacity(0.5)
            poly_3d.shift([6, 0, -0.99])
            top_polygons_vgroup_flat.add(poly_3d)

        def flat_surf_func(u, v):
            return [u, v, 0]
        flat_map_surf = ParametricSurface(flat_surf_func, u_range=[-1, 1], v_range=[-1, 1], resolution=(64, 64))
        flat_map_2 = TexturedSurface(flat_map_surf, graphics_dir + '/baarle_hertog_maps/' + map_filename)
        flat_map_2.set_shading(0, 0, 0).set_opacity(0.8)
        flat_map_2.shift([6, 0, -1.0])
        lines_flat = VGroup()
        for loop in intersection_lines:
            loop[:, 2] = 0
            line = VMobject()
            line.set_points_as_corners(loop)
            line.set_stroke(color='#FF00FF', width=4)
            lines_flat.add(line)
        lines_flat.shift([6, 0, -1.0])
        self.frame.reorient(0, 32, 0, (2.97, -0.05, 0.59), 7.12)
        self.add(group_11, group_12, group_13, group_14)
        self.add(group_21, group_22)
        self.add(group_31, group_32, lines)
        self.add(layer_1_polygons_flat)
        self.add(flat_map_2)
        self.add(top_polygons_vgroup_flat)
        self.add(lines_flat)
        self.wait()
        self.play(self.frame.animate.reorient(-1, 56, 0, (2.97, -0.05, 0.59), 7.12), run_time=8)
        self.wait()
        self.play(FadeOut(group_11), FadeOut(group_12), FadeOut(group_13), FadeOut(group_14), FadeOut(group_21), FadeOut(group_22), FadeOut(group_31), FadeOut(group_32), FadeOut(lines), layer_1_polygons_flat.animate.shift([1.7, 0, 0]), top_polygons_vgroup_flat.animate.shift([-1.7, 0, 0]), lines_flat.animate.shift([-1.7, 0, 0]), flat_map_2.animate.shift([-1.7, 0, 0]), self.frame.animate.reorient(0, 0, 0, (3.06, -1.13, 0.0), 4.36), run_time=6, rate_func=linear)
        self.wait()
        self.wait(20)
        self.embed()