from manimlib import *
from tqdm import tqdm
from pathlib import Path
CHILL_BROWN = '#948979'
YELLOW = '#ffd35a'
BLUE = '#65c8d0'
from manimlib.mobject.svg.svg_mobject import _convert_point_to_3d
from manimlib.logger import log

def get_attention_head(svg_path='/Users/stephen/welch_labs/deepseek/graphics/to_manim', svg_file='mha_2d_segments-', img_path='/Users/stephen/welch_labs/deepseek/hackin/linux_workdir/deepseek/flowchart_graphics'):
    q1 = ImageMobject(str(img_path / 'q_1.png'))
    q1.scale([0.0415, 0.08, 1])
    q1.move_to([-0.2, 0.38, 0])
    k1 = ImageMobject(str(img_path / 'k_1.png'))
    k1.scale([0.0415, 0.08, 1])
    k1.move_to([-0.2, -0.06, 0])
    v1 = ImageMobject(str(img_path / 'v_1.png'))
    v1.scale([0.0415, 0.08, 1])
    v1.move_to([-0.2, -0.48, 0])
    kt = ImageMobject(str(img_path / 'k_1.png'))
    kt.scale([0.0215, 0.035, 1])
    kt.rotate([0, 0, -PI / 2])
    kt.move_to([0.405, 0.305, 0])
    a1 = ImageMobject(str(img_path / 'attention_scores.png'))
    a1.scale([0.055, 0.055, 1])
    a1.move_to([0.66, 0.37, 0])
    a2 = ImageMobject(str(img_path / 'attention_pattern.png'))
    a2.scale([0.13, 0.13, 1])
    a2.move_to([1.27, 0.25, 0])
    z1 = ImageMobject(str(img_path / 'z_1.png'))
    z1.scale([0.0425, 0.08, 1])
    z1.move_to([1.035, -0.48, 0])
    all_images = Group(q1, k1, v1, kt, a1, a2, z1)
    svg_files = list(sorted(svg_path.glob('*' + svg_file + '*')))
    all_labels = Group()
    for svg_file in svg_files:
        svg_image = SVGMobject(str(svg_file))
        all_labels.add(svg_image[1:])
    large_white_connectors = SVGMobject(str(svg_path / 'mha_2d_large_white_connectors_2.svg'))
    return Group(all_images, all_labels, large_white_connectors[1:])

def get_input_x(svg_path='/Users/stephen/welch_labs/deepseek/graphics/to_manim', svg_file='mha_2d_grouping_test.svg', img_path='/Users/stephen/welch_labs/deepseek/hackin/linux_workdir/deepseek/flowchart_graphics'):
    x1 = ImageMobject(str(Path(img_path) / 'input_1_1.png'))
    x1.scale([0.075, 0.125, 1])
    x1.move_to([-1.45, -0.03, 0])
    x2 = ImageMobject(str(Path(img_path) / 'input_2_1.png'))
    x2.scale([0.075, 0.125, 1])
    x2.move_to([-1.225, -0.03, 0])
    all_images = Group(x1, x2)
    svg_image = SVGMobject(str(Path(svg_path) / svg_file))
    x_labels_1 = svg_image[1:45]
    return Group(all_images, x_labels_1)

class poster_1(InteractiveScene):

    def construct(self):
        img_path = Path('/Users/stephen/welch_labs/deepseek/hackin/linux_workdir/deepseek')
        svg_path = Path('/Users/stephen/welch_labs/deepseek/graphics/to_manim')
        i = 0
        a = get_attention_head(svg_path=svg_path, svg_file='mha_2d_segments-', img_path=img_path / 'gpt_2_attention_viz_4' / str(i))
        x = get_input_x(svg_path='/Users/stephen/welch_labs/deepseek/graphics/to_manim', svg_file='mha_2d_grouping_test.svg', img_path=img_path / 'gpt_2_attention_viz_4')
        self.frame.reorient(0, 0, 0, (-1.39, -0.06, -0.0), 1.16)
        self.wait()
        self.play(FadeIn(x[0]))
        self.add(a[1][1])
        self.add(a[1][2])
        self.wait()
        self.add(a[1][16])
        self.wait()
        self.remove(a[1][16])
        self.wait()
        self.play(FadeIn(a[1][6]), self.frame.animate.reorient(0, 0, 0, (-0.65, 0.02, 0.0), 1.36), run_time=2)
        self.wait()
        separate_row_im_path = '/Users/stephen/welch_labs/deepseek/hackin/linux_workdir/deepseek/gpt_2_attention_viz_4'
        q_rows = Group()
        for row_id in range(9):
            q = ImageMobject(separate_row_im_path + '/query_row_' + str(row_id) + '.png')
            q.scale([0.0127, 0.024, 1])
            q.move_to([-0.2, 0.492 - 0.028 * row_id, 0])
            q_rows.add(q)
        k_rows = Group()
        for row_id in range(9):
            k = ImageMobject(separate_row_im_path + '/key_row_' + str(row_id) + '.png')
            k.scale([0.0127, 0.024, 1])
            k.move_to([-0.2, 0.05 - 0.028 * row_id, 0])
            k_rows.add(k)
        self.wait()
        self.play(FadeIn(a[1][3]), FadeIn(a[1][4]), FadeIn(k_rows), FadeIn(q_rows))
        self.wait()
        self.play(*[q_rows[row_id].animate.shift(0.01 * (8 - row_id) * UP) for row_id in range(9)] + [k_rows[row_id].animate.shift(0.01 * (8 - row_id) * UP) for row_id in range(9)] + [self.frame.animate.reorient(0, 0, 0, (-0.23, 0.18, 0.0), 1.2)], lag_ratio=0.2, run_time=3)
        self.wait()
        self.play(FadeOut(x[0]), FadeOut(a[1][1]), FadeOut(a[1][2]), FadeOut(a[1][6]))
        a[1][18].scale(0.595)
        a[1][18].move_to([-0.75, 0.2, 0])
        self.add(a[1][18])
        self.wait()
        a[1][19].scale(0.6)
        a[1][19].move_to([0.49, 0.37, 0])
        self.add(a[1][19][:30])
        self.wait()
        self.add(a[1][19][30:])
        self.wait()
        self.play(FadeOut(a[1][18][:11]), FadeOut(a[1][18][14:32]), FadeOut(a[1][18][40:]), FadeOut(a[1][19]), FadeOut(a[1][3]), FadeOut(a[1][4]), FadeOut(q_rows[:2]), FadeOut(q_rows[3:]), FadeOut(k_rows[0]), FadeOut(k_rows[2:]), run_time=2)
        self.play(q_rows[2].animate.shift(0.12 * DOWN), k_rows[1].animate.shift(0.12 * UP), a[1][18][11:14].animate.shift(0.12 * DOWN), a[1][18][32:40].animate.shift(0.12 * UP))
        self.wait()
        d = Dot(stroke_color=None, fill_color=WHITE)
        d.scale(0.15)
        d.move_to([-0.2, 0.295, 0])
        self.add(d)
        t = Tex('=524.2').set_color(WHITE)
        t.scale(0.1)
        t.move_to([-0.2, 0.12, 0])
        self.add(t)
        self.wait()
        self.remove(d, t)
        self.play(q_rows[2].animate.shift(0.059 * UP), k_rows[1].animate.shift(0.188 * DOWN), FadeOut(a[1][18][11:14]), FadeOut(a[1][18][32:40]))
        self.play(FadeIn(a[0][0]), FadeIn(a[0][1]))
        self.remove(q_rows[2], k_rows[1])
        self.add(a[1][3][:10], a[1][3][-1:])
        self.add(a[1][4][:4], a[1][4][-4:])
        self.wait()
        kt = a[0][1].copy()
        self.play(kt.animate.scale(np.array([0.0215, 0.035, 1]) / np.array([0.0415, 0.08, 1])).rotate([0, 0, -PI / 2]).rotate(PI, UP).move_to([0.405, 0.305, 0]), run_time=2)
        self.add(a[1][7])
        self.wait()
        self.play(FadeIn(a[1][8]), FadeIn(a[0][4]), self.frame.animate.reorient(0, 0, 0, (0.16, 0.17, 0.0), 1.2), run_time=1.2)
        self.wait()
        self.add(a[1][9])
        self.wait()
        self.play(FadeIn(a[0][5]), self.frame.animate.reorient(0, 0, 0, (0.46, 0.18, 0.0), 1.43))
        self.wait()
        self.add(a[1][10])
        self.wait()
        self.play(self.frame.animate.reorient(0, 0, 0, (0, 0, 0.0), 2.0))
        self.remove(a[1][3][:10], a[1][3][-1:])
        self.remove(a[1][4][:4], a[1][4][-4:])
        self.add(a[1][3], a[1][4])
        self.add(x[0], a[1][1], a[1][2], a[1][6])
        self.wait()
        self.play(FadeIn(a[1][17]), FadeIn(a[1][5]), FadeIn(a[0][2]))
        self.wait()
        self.play(self.frame.animate.reorient(0, 0, 0, (-0.22, -0.49, -0.0), 1.15))
        self.wait()
        self.play(self.frame.animate.reorient(0, 0, 0, (-0.16, -0.09, 0.0), 1.35))
        self.wait()
        self.play(self.frame.animate.reorient(0, 0, 0, (0, 0, 0.0), 2.0))
        self.wait()
        self.add(a[1][11])
        self.wait()
        self.play(FadeIn(a[0][6]), FadeIn(a[1][12]))
        self.wait()
        self.play(Write(a[1][0]), run_time=1)
        self.wait()
        head_0_3d_images = Group(a[0], kt)
        head_0_3d_vectors = Group(a[1][0], a[1][3:6], a[1][6:13], a[1][17])
        head_0_3d = Group(head_0_3d_images, head_0_3d_vectors)
        self.remove(x, a[1][1], a[1][2])
        head_0_3d.rotate([PI / 2, 0, 0], axis=RIGHT)
        self.frame.reorient(0, 90, 0, (0, 0, 0.0), 2.0)
        self.wait()
        attention_heads = Group()
        spacing = 0.25
        for i in range(1, 12):
            a = get_attention_head(svg_path=svg_path, svg_file='mha_2d_segments-', img_path=img_path / 'gpt_2_attention_viz_4' / str(i))
            a_select = Group(a[0], a[1][0], a[1][3:6], a[1][6:13], a[1][17])
            a_select.rotate([PI / 2, 0, 0], axis=RIGHT)
            a_select.move_to([0.27, spacing * i, 0])
            attention_heads.add(a_select)
        for i in range(10, -1, -1):
            self.add(attention_heads[i])
        self.add(head_0_3d)
        for i in range(10, -1, -1):
            attention_heads[i].shift(6 * LEFT)
        self.play(self.frame.animate.reorient(-38, 72, 0, (-0.37, 0.29, 0.02), 2.56), run_time=3)
        self.wait(0)
        for i in range(11):
            self.play(attention_heads[i].animate.shift(6 * RIGHT), run_time=1, rate_func=linear)
        self.wait()
        self.play(self.frame.animate.reorient(36, 83, 0, (0.8, 0.62, -0.11), 2.65), run_time=6)
        self.wait()
        out_matrices = [attention_heads[i][0][-1] for i in range(10, -1, -1)] + [head_0_3d[0][0][-1]]
        self.play(*[o.animate.scale(0.2).move_to([3 + i * 0.2, 0, 0]) for i, o in enumerate(out_matrices)] + [self.frame.animate.reorient(-1, 86, 0, (4.32, 0.84, -0.21), 3.29)], run_time=3)
        self.wait()
        p20_overlay = SVGMobject('/Users/stephen/welch_labs/deepseek/graphics/to_manim/p20_svg_overay_1.svg')[1:]
        p20_overlay.rotate([PI / 2, 0, 0], axis=RIGHT)
        p20_overlay.scale(1.3)
        p20_overlay.move_to([4.62, 0, -0.26])
        self.add(p20_overlay)
        self.wait(20)
        self.embed()

class poster_1_b(InteractiveScene):

    def construct(self):
        img_path = Path('/Users/stephen/welch_labs/deepseek/hackin/linux_workdir/deepseek')
        svg_path = Path('/Users/stephen/welch_labs/deepseek/graphics/to_manim')
        attention_heads = Group()
        spacing = 0.25
        for i in range(12):
            a = get_attention_head(svg_path=svg_path, svg_file='mha_2d_segments-', img_path=img_path / 'gpt_2_attention_viz_4' / str(i))
            a.rotate([PI / 2, 0, 0], axis=RIGHT)
            a.move_to([0.27, spacing * i, 0])
            attention_heads.add(a)
        for i in range(11, 0, -1):
            self.add(attention_heads[i][0])
            self.add(attention_heads[i][1][20])
            self.add(attention_heads[i][1][13])
            self.add(attention_heads[i][1][21])
        i = 0
        self.add(attention_heads[i][0])
        self.add(attention_heads[i][1][3:6])
        self.add(attention_heads[i][1][6:13])
        self.add(attention_heads[i][1][17])
        self.frame.reorient(-38, 59, 0, (0.12, 0.93, -0.18), 2.93)
        self.wait(20)
        self.embed()

class poster_1_a(InteractiveScene):

    def construct(self):
        img_path = Path('/Users/stephen/welch_labs/deepseek/hackin/linux_workdir/deepseek')
        svg_path = Path('/Users/stephen/welch_labs/deepseek/graphics/to_manim')
        i = 0
        a = get_attention_head(svg_path=svg_path, svg_file='mha_2d_segments-', img_path=img_path / 'gpt_2_attention_viz_4' / str(i))
        x = get_input_x(svg_path='/Users/stephen/welch_labs/deepseek/graphics/to_manim', svg_file='mha_2d_grouping_test.svg', img_path='/Users/stephen/welch_labs/deepseek/hackin/linux_workdir/deepseek/flowchart_graphics')
        self.frame.reorient(0, 0, 0, (-1.39, -0.06, -0.0), 1.16)
        self.wait()
        self.play(FadeIn(x[0]))
        self.add(a[1][1])
        self.add(a[1][2])
        self.wait()
        self.add(a[1][16])
        self.wait()
        self.remove(a[1][16])
        self.wait()
        self.play(FadeIn(a[1][6]), self.frame.animate.reorient(0, 0, 0, (-0.65, 0.02, 0.0), 1.36), run_time=2)
        self.wait()
        separate_row_im_path = '/Users/stephen/welch_labs/deepseek/hackin/linux_workdir/deepseek/gpt_2_attention_viz_4'
        q_rows = Group()
        for row_id in range(9):
            q = ImageMobject(separate_row_im_path + '/query_row_' + str(row_id) + '.png')
            q.scale([0.0127, 0.024, 1])
            q.move_to([-0.2, 0.492 - 0.028 * row_id, 0])
            q_rows.add(q)
        k_rows = Group()
        for row_id in range(9):
            k = ImageMobject(separate_row_im_path + '/key_row_' + str(row_id) + '.png')
            k.scale([0.0127, 0.024, 1])
            k.move_to([-0.2, 0.05 - 0.028 * row_id, 0])
            k_rows.add(k)
        self.wait()
        self.play(FadeIn(a[1][3]), FadeIn(a[1][4]), FadeIn(k_rows), FadeIn(q_rows))
        self.wait()
        self.play(*[q_rows[row_id].animate.shift(0.01 * (8 - row_id) * UP) for row_id in range(9)] + [k_rows[row_id].animate.shift(0.01 * (8 - row_id) * UP) for row_id in range(9)] + [self.frame.animate.reorient(0, 0, 0, (-0.23, 0.18, 0.0), 1.2)], lag_ratio=0.2, run_time=3)
        self.wait()
        self.play(FadeOut(x[0]), FadeOut(a[1][1]), FadeOut(a[1][2]), FadeOut(a[1][6]))
        a[1][18].scale(0.595)
        a[1][18].move_to([-0.75, 0.2, 0])
        self.add(a[1][18])
        self.wait()
        a[1][19].scale(0.6)
        a[1][19].move_to([0.49, 0.37, 0])
        self.add(a[1][19][:30])
        self.wait()
        self.add(a[1][19][30:])
        self.wait()
        self.play(FadeOut(a[1][18][:11]), FadeOut(a[1][18][14:32]), FadeOut(a[1][18][40:]), FadeOut(a[1][19]), FadeOut(a[1][3]), FadeOut(a[1][4]), FadeOut(q_rows[:2]), FadeOut(q_rows[3:]), FadeOut(k_rows[0]), FadeOut(k_rows[2:]), run_time=2)
        self.play(q_rows[2].animate.shift(0.12 * DOWN), k_rows[1].animate.shift(0.12 * UP), a[1][18][11:14].animate.shift(0.12 * DOWN), a[1][18][32:40].animate.shift(0.12 * UP))
        self.wait()
        d = Dot(stroke_color=None, fill_color=WHITE)
        d.scale(0.15)
        d.move_to([-0.2, 0.295, 0])
        self.add(d)
        t = Tex('=524.2').set_color(WHITE)
        t.scale(0.1)
        t.move_to([-0.2, 0.12, 0])
        self.add(t)
        self.wait()
        self.remove(d, t)
        self.play(q_rows[2].animate.shift(0.059 * UP), k_rows[1].animate.shift(0.188 * DOWN), FadeOut(a[1][18][11:14]), FadeOut(a[1][18][32:40]))
        self.play(FadeIn(a[0][0]), FadeIn(a[0][1]))
        self.remove(q_rows[2], k_rows[1])
        self.add(a[1][3][:10], a[1][3][-1:])
        self.add(a[1][4][:4], a[1][4][-4:])
        self.wait()
        kt = a[0][1].copy()
        self.play(kt.animate.scale(np.array([0.0215, 0.035, 1]) / np.array([0.0415, 0.08, 1])).rotate([0, 0, -PI / 2]).rotate(PI, UP).move_to([0.405, 0.305, 0]), run_time=2)
        self.add(a[1][7])
        self.wait()
        self.play(FadeIn(a[1][8]), FadeIn(a[0][4]), self.frame.animate.reorient(0, 0, 0, (0.16, 0.17, 0.0), 1.2), run_time=1.2)
        self.wait()
        self.add(a[1][9])
        self.wait()
        self.play(FadeIn(a[0][5]), self.frame.animate.reorient(0, 0, 0, (0.46, 0.18, 0.0), 1.43))
        self.wait()
        self.add(a[1][10])
        self.wait()
        self.play(self.frame.animate.reorient(0, 0, 0, (0, 0, 0.0), 2.0))
        self.remove(a[1][3][:10], a[1][3][-1:])
        self.remove(a[1][4][:4], a[1][4][-4:])
        self.add(a[1][3], a[1][4])
        self.add(x[0], a[1][1], a[1][2], a[1][6])
        self.wait()
        self.play(FadeIn(a[1][17]), FadeIn(a[1][5]), FadeIn(a[0][2]))
        self.wait()
        self.add(a[1][11])
        self.wait()
        self.play(FadeIn(a[0][6]), FadeIn(a[1][12]))
        self.wait()
        self.wait()
        head_0_3d_images = Group(a[0], kt)
        head_0_3d_vectors = Group(a[1][3:6], a[1][6:13], a[1][17])
        head_0_3d = Group(head_0_3d_images, head_0_3d_vectors)
        self.remove(x, a[1][1], a[1][2])
        head_0_3d.rotate([PI / 2, 0, 0], axis=RIGHT)
        self.frame.reorient(0, 90, 0, (0, 0, 0.0), 2.0)
        self.wait()
        attention_heads = Group()
        spacing = 0.25
        for i in range(1, 12):
            a = get_attention_head(svg_path=svg_path, svg_file='mha_2d_segments-', img_path=img_path / 'gpt_2_attention_viz_4' / str(i))
            a_select = Group(a[0], a[1][3:7], a[1][13], a[1][17])
            a_select.rotate([PI / 2, 0, 0], axis=RIGHT)
            a_select.move_to([0.27, spacing * i, 0])
            attention_heads.add(a_select)
        for i in range(10, -1, -1):
            self.add(attention_heads[i])
        self.add(head_0_3d)
        for i in range(10, -1, -1):
            attention_heads[i].shift(6 * LEFT)
        self.wait()
        self.play(self.frame.animate.reorient(-38, 72, 0, (-0.37, 0.29, 0.02), 2.56), run_time=3)
        for i in range(11):
            self.play(attention_heads[i].animate.shift(6 * RIGHT), run_time=1, rate_func=linear)
        self.wait()
        self.frame.reorient(51, 74, 0, (0.05, 0.82, -0.29), 3.44)
        self.wait()
        self.wait(20)
        self.embed()